import { Platform, StyleSheet } from 'react-native';

export function createStyles(isDarkTheme: boolean) {
  const colors = isDarkTheme
    ? {
        page: '#081338',
        headerTitle: '#f8fbff',
        iconBorder: 'rgba(255,255,255,0.16)',
        iconBg: 'rgba(255,255,255,0.06)',
        dotConnected: '#059669',
        dotConnecting: '#D97706',
        dotDisconnected: '#C4C4C0',
        chipConnectedBg: 'rgba(5,150,105,0.17)',
        chipConnectedText: '#75e2ba',
        chipConnectingBg: 'rgba(217,119,6,0.17)',
        chipConnectingText: '#f1c58b',
        chipDisconnectedBg: 'rgba(255,255,255,0.09)',
        chipDisconnectedText: '#bccae2',
        panelBg: '#12214a',
        panelBorder: 'rgba(255,255,255,0.12)',
        label: '#9eb1d2',
        inputBorder: 'rgba(255,255,255,0.16)',
        inputBorderFocused: '#2563EB',
        inputBg: '#0f1c3f',
        inputText: '#f8fbff',
        connectBtn: '#2563EB',
        smallBtnDisabled: '#5d6f94',
        cardBg: '#12214a',
        cardBorder: 'rgba(255,255,255,0.12)',
        recordingBorder: 'rgba(220,38,38,0.28)',
        textPrimary: '#ffffff',
        textSecondary: '#b8c9e6',
        placeholder: '#95a8ca',
        loading: '#b8c9e6',
        historyDateLine: 'rgba(255,255,255,0.14)',
        historyDateText: '#95a8ca',
        historyMetaText: '#95a8ca',
        historyWaitingDot: '#2563EB',
        assistantAvatarBg: 'rgba(37,99,235,0.42)',
        assistantAvatarBorder: 'transparent',
        turnUser: '#ffffff',
        turnUserBubbleBg: '#2563EB',
        turnUserBubbleBorder: 'rgba(37,99,235,0.45)',
        turnAssistantBubbleBg: '#16274a',
        turnAssistantBubbleBorder: 'rgba(255,255,255,0.12)',
        turnAssistantErrorBorder: 'rgba(220,38,38,0.4)',
        tagOkBg: 'rgba(5,150,105,0.17)',
        tagOkText: '#75e2ba',
        tagWaitingBg: 'rgba(217,119,6,0.16)',
        tagWaitingText: '#f1c58b',
        tagErrorBg: 'rgba(220,38,38,0.15)',
        tagErrorText: '#ffb0b0',
        errorBg: '#15213f',
        errorBorder: '#DC2626',
        errorText: '#ffb0b0',
        topBannerBg: 'rgba(220,38,38,0.14)',
        topBannerBorder: 'rgba(220,38,38,0.42)',
        topBannerText: '#ffb0b0',
        topBannerSpeechBg: 'rgba(217,119,6,0.16)',
        topBannerSpeechBorder: 'rgba(217,119,6,0.38)',
        topBannerActionBg: 'rgba(255,255,255,0.10)',
        topBannerActionBorder: 'rgba(255,255,255,0.22)',
        topBannerActionIcon: '#dbe7ff',
        roundBorder: 'rgba(255,255,255,0.22)',
        micRound: '#2563EB',
        recordingRound: '#DC2626',
        sendRound: '#059669',
        roundDisabled: '#243a63',
        quickActionBg: '#059669',
        quickActionBorder: 'rgba(255,255,255,0.28)',
        quickActionText: '#ffffff',
        quickTooltipBg: '#1a2f5a',
        quickTooltipBorder: 'rgba(110,231,183,0.34)',
        quickTooltipText: '#e8fff7',
        bottomStateNeutral: '#b8c9e6',
        bottomStateConnecting: '#f1c58b',
        bottomStateDisconnected: '#95a8ca',
        bottomStateRecording: '#ffb0b0',
        bottomStateSending: '#9ec0ff',
        bottomStateRetrying: '#f1c58b',
        bottomStateComplete: '#75e2ba',
        bottomStateError: '#ffb0b0',
        bottomStateDetail: '#95a8ca',
        bottomDockBg: 'transparent',
        bottomDockBorder: 'rgba(255,255,255,0.08)',
      }
    : {
        page: '#F5F5F0',
        headerTitle: '#1A1A1A',
        iconBorder: 'rgba(0,0,0,0.12)',
        iconBg: '#EEEEEA',
        dotConnected: '#059669',
        dotConnecting: '#D97706',
        dotDisconnected: '#C4C4C0',
        chipConnectedBg: 'rgba(5,150,105,0.07)',
        chipConnectedText: '#059669',
        chipConnectingBg: 'rgba(217,119,6,0.07)',
        chipConnectingText: '#D97706',
        chipDisconnectedBg: 'rgba(0,0,0,0.03)',
        chipDisconnectedText: '#5C5C5C',
        panelBg: '#FFFFFF',
        panelBorder: 'rgba(0,0,0,0.05)',
        label: '#70706A',
        inputBorder: 'rgba(0,0,0,0.06)',
        inputBorderFocused: '#2563EB',
        inputBg: '#EEEEEA',
        inputText: '#1A1A1A',
        connectBtn: '#2563EB',
        smallBtnDisabled: '#C4C4C0',
        cardBg: '#FFFFFF',
        cardBorder: 'rgba(0,0,0,0.05)',
        recordingBorder: 'rgba(220,38,38,0.18)',
        textPrimary: '#1A1A1A',
        textSecondary: '#5C5C5C',
        placeholder: '#A1A19B',
        loading: '#5C5C5C',
        historyDateLine: 'rgba(0,0,0,0.06)',
        historyDateText: '#A1A19B',
        historyMetaText: '#999999',
        historyWaitingDot: '#2563EB',
        assistantAvatarBg: 'rgba(37,99,235,0.14)',
        assistantAvatarBorder: 'transparent',
        turnUser: '#FFFFFF',
        turnUserBubbleBg: '#2563EB',
        turnUserBubbleBorder: 'rgba(37,99,235,0.18)',
        turnAssistantBubbleBg: '#FFFFFF',
        turnAssistantBubbleBorder: 'rgba(0,0,0,0.05)',
        turnAssistantErrorBorder: 'rgba(220,38,38,0.15)',
        tagOkBg: 'rgba(5,150,105,0.07)',
        tagOkText: '#059669',
        tagWaitingBg: 'rgba(217,119,6,0.07)',
        tagWaitingText: '#D97706',
        tagErrorBg: 'rgba(220,38,38,0.06)',
        tagErrorText: '#DC2626',
        errorBg: '#FFFFFF',
        errorBorder: '#DC2626',
        errorText: '#DC2626',
        topBannerBg: 'rgba(220,38,38,0.08)',
        topBannerBorder: 'rgba(220,38,38,0.2)',
        topBannerText: '#B91C1C',
        topBannerSpeechBg: 'rgba(217,119,6,0.08)',
        topBannerSpeechBorder: 'rgba(217,119,6,0.2)',
        topBannerActionBg: '#F7F7F4',
        topBannerActionBorder: 'rgba(0,0,0,0.1)',
        topBannerActionIcon: '#7f1d1d',
        roundBorder: 'rgba(255,255,255,0.52)',
        micRound: '#2563EB',
        recordingRound: '#DC2626',
        sendRound: '#059669',
        roundDisabled: '#C4C4C0',
        quickActionBg: '#059669',
        quickActionBorder: 'rgba(255,255,255,0.58)',
        quickActionText: '#ffffff',
        quickTooltipBg: '#ffffff',
        quickTooltipBorder: 'rgba(5,150,105,0.24)',
        quickTooltipText: '#065f46',
        bottomStateNeutral: '#5C5C5C',
        bottomStateConnecting: '#B45309',
        bottomStateDisconnected: '#8A8A84',
        bottomStateRecording: '#B91C1C',
        bottomStateSending: '#1D4ED8',
        bottomStateRetrying: '#B45309',
        bottomStateComplete: '#047857',
        bottomStateError: '#B91C1C',
        bottomStateDetail: '#8A8A84',
        bottomDockBg: 'transparent',
        bottomDockBorder: 'rgba(0,0,0,0.04)',
      };

  const surfaceShadow = {
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  } as const;

  const fabShadow = {
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 28,
    elevation: 9,
  } as const;

  const recordingFabShadow = {
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 28,
    elevation: 9,
  } as const;

  const quickFabShadow = {
    shadowColor: '#059669',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 7,
  } as const;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.page,
    },
    keyboardWrap: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 8,
      gap: 8,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    logoBadge: {
      width: 26,
      height: 26,
      borderRadius: 7,
      overflow: 'hidden',
    },
    logoBadgeImage: {
      width: '100%',
      height: '100%',
    },
    headerTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.headerTitle,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    statusChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderWidth: 0,
      borderColor: colors.iconBorder,
    },
    statusChipConnected: {
      backgroundColor: colors.chipConnectedBg,
    },
    statusChipConnecting: {
      backgroundColor: colors.chipConnectingBg,
    },
    statusChipDisconnected: {
      backgroundColor: colors.chipDisconnectedBg,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    statusDotConnected: {
      backgroundColor: colors.dotConnected,
    },
    statusDotConnecting: {
      backgroundColor: colors.dotConnecting,
    },
    statusDotDisconnected: {
      backgroundColor: colors.dotDisconnected,
    },
    iconButton: {
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: colors.iconBorder,
      backgroundColor: colors.iconBg,
    },
    iconButtonActive: {
      borderColor: colors.inputBorderFocused,
    },
    iconButtonDisabled: {
      opacity: 0.45,
    },
    statusChipText: {
      fontSize: 11,
      fontWeight: '600',
    },
    statusChipTextConnected: {
      color: colors.chipConnectedText,
    },
    statusChipTextConnecting: {
      color: colors.chipConnectingText,
    },
    statusChipTextDisconnected: {
      color: colors.chipDisconnectedText,
    },
    settingsScreenContainer: {
      flex: 1,
      backgroundColor: colors.page,
    },
    settingsScreenHeader: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    settingsScreenHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexShrink: 1,
    },
    settingsScreenTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.headerTitle,
    },
    settingsStatusChip: {
      maxWidth: 184,
      minHeight: 30,
      borderRadius: 999,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 9,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    settingsStatusChipPending: {
      borderColor: colors.inputBorderFocused,
    },
    settingsStatusChipError: {
      borderColor: isDarkTheme ? 'rgba(220,38,38,0.44)' : 'rgba(220,38,38,0.24)',
    },
    settingsStatusChipText: {
      flexShrink: 1,
      fontSize: 10,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    settingsStatusChipTextError: {
      color: colors.errorText,
    },
    settingsScreenKeyboardWrap: {
      flex: 1,
    },
    settingsScreenScroll: {
      flex: 1,
    },
    settingsScreenScrollContent: {
      paddingHorizontal: 12,
      paddingTop: 4,
      paddingBottom: 16,
    },
    settingsScreenScrollContentKeyboardOpen: {
      paddingBottom: Platform.OS === 'ios' ? 300 : 220,
    },
    gatewayPanel: {
      borderRadius: 16,
      backgroundColor: colors.panelBg,
      padding: 12,
      borderWidth: 1.5,
      borderColor: colors.panelBorder,
      ...surfaceShadow,
    },
    settingsSection: {
      width: '100%',
    },
    sectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginBottom: 4,
    },
    settingsSectionSpaced: {
      marginTop: 14,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.panelBorder,
    },
    settingsSectionFocused: {
      marginTop: 0,
      paddingTop: 0,
      borderTopWidth: 0,
    },
    settingsSectionTitle: {
      fontSize: 14,
      color: colors.textPrimary,
      fontWeight: '700',
      marginBottom: 0,
    },
    onboardingSection: {
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      borderRadius: 12,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 10,
      paddingVertical: 9,
      marginBottom: 12,
    },
    onboardingDescription: {
      marginTop: 2,
      fontSize: 11,
      color: colors.label,
      lineHeight: 15,
    },
    onboardingStepList: {
      marginTop: 7,
      gap: 5,
    },
    onboardingStepRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    onboardingStepText: {
      flex: 1,
      fontSize: 11,
      color: colors.textSecondary,
      lineHeight: 15,
    },
    onboardingStepTextDone: {
      color: colors.textPrimary,
      fontWeight: '600',
    },
    onboardingActionRow: {
      marginTop: 8,
      flexDirection: 'row',
      gap: 6,
      alignItems: 'stretch',
    },
    onboardingSecondaryButton: {
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
    },
    onboardingSecondaryButtonDisabled: {
      opacity: 0.55,
    },
    onboardingSecondaryButtonText: {
      color: colors.textSecondary,
      fontWeight: '700',
      fontSize: 12,
    },
    onboardingSkipButton: {
      marginTop: 6,
      alignSelf: 'flex-end',
      paddingHorizontal: 4,
      paddingVertical: 2,
    },
    onboardingSkipButtonText: {
      fontSize: 11,
      color: colors.label,
      fontWeight: '600',
    },
    quickTextSectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 2,
    },
    quickTextDoneButton: {
      minHeight: 28,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 9,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    quickTextDoneButtonText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    settingsOptionRow: {
      flexDirection: 'row',
      gap: 6,
      marginTop: 1,
    },
    settingsOptionButton: {
      flex: 1,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      backgroundColor: colors.inputBg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 38,
      paddingVertical: 7,
      paddingHorizontal: 10,
      gap: 6,
    },
    settingsOptionButtonSelected: {
      borderColor: colors.inputBorderFocused,
      backgroundColor: isDarkTheme
        ? 'rgba(37,99,235,0.24)'
        : 'rgba(37,99,235,0.10)',
    },
    settingsOptionLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    settingsOptionLabelSelected: {
      color: colors.textPrimary,
    },
    label: {
      fontSize: 11,
      color: colors.label,
      marginBottom: 4,
    },
    labelSpacing: {
      marginTop: 8,
    },
    input: {
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      color: colors.inputText,
      backgroundColor: colors.inputBg,
      fontSize: 13,
    },
    tokenInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 0,
      paddingLeft: 12,
      paddingRight: 6,
    },
    tokenInputField: {
      flex: 1,
      minHeight: 40,
      color: colors.inputText,
      fontSize: 13,
      paddingVertical: 9,
      paddingRight: 8,
    },
    tokenVisibilityButton: {
      width: 30,
      height: 30,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.iconBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    inputFocused: {
      borderColor: colors.inputBorderFocused,
    },
    languagePickerRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 1,
    },
    languageOptionButton: {
      flex: 1,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      borderRadius: 10,
      backgroundColor: colors.inputBg,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 52,
      paddingVertical: 7,
      paddingHorizontal: 10,
      gap: 3,
    },
    languageOptionButtonSelected: {
      borderColor: colors.inputBorderFocused,
      backgroundColor: isDarkTheme
        ? 'rgba(37,99,235,0.24)'
        : 'rgba(37,99,235,0.10)',
    },
    languageOptionLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    languageOptionLabelSelected: {
      color: colors.textPrimary,
    },
    languageOptionCode: {
      fontSize: 9,
      color: colors.label,
    },
    languageOptionCodeSelected: {
      color: colors.inputBorderFocused,
      fontWeight: '600',
    },
    quickTextConfigRow: {
      flexDirection: 'column',
      gap: 10,
      marginTop: 4,
    },
    quickTextConfigItem: {
      width: '100%',
    },
    quickTextConfigInput: {
      minHeight: 72,
      maxHeight: 120,
      paddingTop: 8,
    },
    quickTextIconLabel: {
      marginTop: 6,
    },
    quickTextIconPickerRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 6,
    },
    quickTextIconOptionButton: {
      width: 34,
      height: 34,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickTextIconOptionButtonSelected: {
      borderColor: colors.inputBorderFocused,
      backgroundColor: isDarkTheme
        ? 'rgba(37,99,235,0.22)'
        : 'rgba(37,99,235,0.10)',
    },
    sessionActionButton: {
      minHeight: 36,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sessionActionButtonDisabled: {
      opacity: 0.55,
    },
    sessionActionButtonText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    sessionButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    sessionActionRow: {
      marginTop: 8,
      flexDirection: 'row',
      gap: 6,
    },
    sessionActionButtonWide: {
      flex: 1,
    },
    sessionChipPrimary: {
      gap: 4,
    },
    sessionChipActionRow: {
      marginTop: 4,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 6,
    },
    sessionChipActionButton: {
      width: 30,
      height: 30,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sessionChipActionButtonDisabled: {
      opacity: 0.55,
    },
    sessionRenameRow: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    sessionRenameRowInline: {
      marginTop: 6,
    },
    sessionRenameInput: {
      flex: 1,
      minHeight: 38,
      paddingVertical: 7,
      fontSize: 13,
    },
    sessionRenameActionButton: {
      minHeight: 32,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sessionRenameActionButtonDisabled: {
      opacity: 0.55,
    },
    sessionRenameActionButtonText: {
      fontSize: 11,
      color: colors.textSecondary,
      fontWeight: '600',
    },
    sessionHintText: {
      marginTop: 6,
      fontSize: 10,
      color: colors.label,
      lineHeight: 14,
    },
    sessionHintTextWarning: {
      color: colors.errorText,
    },
    sessionListColumn: {
      marginTop: 8,
      paddingVertical: 2,
      gap: 8,
    },
    sessionChip: {
      width: '100%',
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 11,
      paddingVertical: 8,
      gap: 6,
    },
    sessionChipActive: {
      borderColor: colors.inputBorderFocused,
      backgroundColor: isDarkTheme
        ? 'rgba(37,99,235,0.24)'
        : 'rgba(37,99,235,0.10)',
    },
    sessionChipDisabled: {
      opacity: 0.65,
    },
    sessionChipTitle: {
      fontSize: 12,
      color: colors.textPrimary,
      fontWeight: '600',
      flexShrink: 1,
    },
    sessionChipTitleActive: {
      color: colors.textPrimary,
    },
    sessionChipTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    sessionChipBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    sessionChipBadge: {
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      minWidth: 18,
      minHeight: 18,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 2,
      paddingVertical: 2,
    },
    sessionChipBadgeCurrent: {
      borderColor: colors.inputBorderFocused,
      backgroundColor: isDarkTheme
        ? 'rgba(37,99,235,0.24)'
        : 'rgba(37,99,235,0.12)',
    },
    sessionChipBadgePinned: {
      borderColor: isDarkTheme ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.12)',
    },
    sessionChipMeta: {
      fontSize: 10,
      color: colors.label,
      lineHeight: 14,
    },
    sessionChipMetaActive: {
      color: colors.inputBorderFocused,
    },
    connectionRow: {
      marginTop: 8,
      flexDirection: 'row',
      gap: 8,
      alignItems: 'stretch',
      width: '100%',
    },
    autoConnectLoadingRow: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    autoConnectLoadingText: {
      fontSize: 11,
      color: colors.loading,
      fontWeight: '600',
    },
    gatewayDiagnosticBox: {
      marginTop: 8,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      paddingHorizontal: 9,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 7,
    },
    gatewayDiagnosticTextWrap: {
      flex: 1,
      gap: 2,
    },
    gatewayDiagnosticSummary: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textPrimary,
      lineHeight: 15,
    },
    gatewayDiagnosticHint: {
      fontSize: 10,
      color: colors.textSecondary,
      lineHeight: 14,
    },
    smallButton: {
      borderRadius: 9,
      minHeight: 40,
      paddingHorizontal: 12,
      paddingVertical: 8,
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
      borderWidth: 0,
      borderColor: 'transparent',
    },
    connectButton: {
      backgroundColor: colors.connectBtn,
    },
    smallButtonText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 12,
    },
    smallButtonDisabled: {
      backgroundColor: colors.smallBtnDisabled,
    },
    headerBoundary: {
      height: 1,
      backgroundColor: isDarkTheme
        ? 'rgba(143,167,210,0.26)'
        : 'rgba(108,122,148,0.26)',
      marginTop: 1,
      marginBottom: 3,
      opacity: 0.9,
    },
    topBanner: {
      width: '100%',
      minHeight: 30,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: colors.topBannerBorder,
      backgroundColor: colors.topBannerBg,
      paddingHorizontal: 8,
      paddingVertical: 4,
      marginBottom: 4,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    topBannerSpeech: {
      borderColor: colors.topBannerSpeechBorder,
      backgroundColor: colors.topBannerSpeechBg,
    },
    topBannerIcon: {
      color: colors.topBannerText,
    },
    topBannerText: {
      flex: 1,
      color: colors.topBannerText,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '600',
    },
    topBannerActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      flexShrink: 0,
    },
    topBannerActionButton: {
      width: 24,
      height: 24,
      borderRadius: 7,
      borderWidth: 1,
      borderColor: colors.topBannerActionBorder,
      backgroundColor: colors.topBannerActionBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    topBannerActionButtonDisabled: {
      opacity: 0.5,
    },
    topBannerActionIcon: {
      color: colors.topBannerActionIcon,
    },
    main: {
      flex: 1,
      gap: 8,
    },
    card: {
      borderRadius: 20,
      backgroundColor: colors.cardBg,
      borderWidth: 1.5,
      borderColor: colors.cardBorder,
      padding: 14,
      ...surfaceShadow,
    },
    recordingCard: {
      borderColor: colors.recordingBorder,
    },
    historyCard: {
      flex: 1,
      minHeight: 220,
    },
    historyCardFlat: {
      backgroundColor: 'transparent',
      borderWidth: 0,
      borderColor: 'transparent',
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: 2,
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    transcriptCardExpanded: {
      flex: 1,
      minHeight: 0,
    },
    transcriptCardCompact: {
      paddingTop: 8,
      paddingBottom: 8,
    },
    transcriptEditor: {
      minHeight: 96,
      gap: 6,
    },
    transcriptEditorCompact: {
      minHeight: 48,
      gap: 0,
    },
    transcriptEditorExpanded: {
      flex: 1,
      minHeight: 0,
    },
    transcriptInput: {
      minHeight: 80,
      borderRadius: 0,
      borderWidth: 0,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
      color: colors.textPrimary,
      paddingHorizontal: 2,
      paddingVertical: 0,
      fontSize: 15,
      lineHeight: 22,
    },
    transcriptInputCompact: {
      minHeight: 38,
      lineHeight: 20,
    },
    transcriptInputExpanded: {
      flex: 1,
      minHeight: 0,
    },
    transcriptInputDisabled: {
      opacity: 0.85,
    },
    interimText: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
      fontStyle: 'italic',
      paddingHorizontal: 2,
    },
    placeholder: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.placeholder,
      textAlign: 'center',
      paddingVertical: 48,
    },
    historyMetaTopRow: {
      minHeight: 20,
      marginBottom: 4,
      paddingRight: 36,
      justifyContent: 'center',
    },
    historyMetaTopText: {
      fontSize: 11,
      color: colors.historyMetaText,
    },
    historyRefreshButtonFloating: {
      width: 26,
      height: 26,
      borderRadius: 9,
      position: 'absolute',
      top: 0,
      right: 0,
      zIndex: 2,
    },
    historyScrollToBottomButtonFloating: {
      width: 32,
      height: 32,
      borderRadius: 10,
      position: 'absolute',
      right: 0,
      bottom: 6,
      zIndex: 3,
    },
    chatList: {
      paddingBottom: 10,
      gap: 0,
    },
    chatListWithScrollButton: {
      paddingBottom: 0,
    },
    historyDateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingTop: 8,
      paddingBottom: 6,
    },
    historyDateLine: {
      flex: 1,
      height: 1,
      backgroundColor: colors.historyDateLine,
    },
    historyDateText: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.historyDateText,
    },
    historyTurnGroup: {
      marginBottom: 10,
      gap: 0,
    },
    historyTurnGroupLast: {
      marginBottom: 0,
    },
    historyUserRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginBottom: 4,
    },
    historyAssistantRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 6,
      marginBottom: 2,
    },
    assistantAvatar: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.assistantAvatarBg,
      borderWidth: 1,
      borderColor: colors.assistantAvatarBorder,
    },
    historyMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingTop: 0,
    },
    historyMetaDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    historyMetaDotOk: {
      backgroundColor: colors.dotConnected,
    },
    historyMetaDotWaiting: {
      backgroundColor: colors.historyWaitingDot,
    },
    historyMetaDotError: {
      backgroundColor: colors.errorBorder,
    },
    historyMetaText: {
      fontSize: 10,
      color: colors.historyMetaText,
    },
    turnUser: {
      color: colors.turnUser,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
    },
    turnUserBubble: {
      maxWidth: '78%',
      backgroundColor: colors.turnUserBubbleBg,
      borderWidth: 0,
      borderColor: 'transparent',
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderBottomRightRadius: 4,
      borderBottomLeftRadius: 18,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    turnAssistantBubble: {
      flexShrink: 1,
      maxWidth: '78%',
      backgroundColor: colors.turnAssistantBubbleBg,
      borderWidth: 0,
      borderColor: 'transparent',
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderBottomRightRadius: 18,
      borderBottomLeftRadius: 4,
      paddingHorizontal: 12,
      paddingVertical: 10,
      ...surfaceShadow,
    },
    turnAssistantBubbleError: {
      borderWidth: 1.5,
      borderColor: colors.turnAssistantErrorBorder,
    },
    bottomDock: {
      alignItems: 'center',
      paddingTop: 10,
      paddingBottom: 6,
      gap: 8,
      width: '100%',
      borderTopWidth: 1,
      borderTopColor: colors.bottomDockBorder,
      backgroundColor: colors.bottomDockBg,
      borderTopLeftRadius: 14,
      borderTopRightRadius: 14,
    },
    bottomDockComposing: {
      paddingTop: 8,
      paddingBottom: 4,
      gap: 4,
    },
    bottomDockKeyboardOpen: {
      paddingTop: 12,
      paddingBottom: 12,
    },
    bottomDockKeyboardCompact: {
      paddingTop: 6,
      paddingBottom: 4,
      gap: 4,
    },
    bottomActionRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
    },
    keyboardActionRow: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    keyboardActionButton: {
      minHeight: 44,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBg,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 14,
    },
    keyboardActionButtonWide: {
      flex: 1,
    },
    keyboardActionButtonSingle: {
      minWidth: 100,
    },
    keyboardActionButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    keyboardClearActionButtonText: {
      color: isDarkTheme ? '#ffb0b0' : '#DC2626',
      fontWeight: '700',
    },
    keyboardSendActionButton: {
      backgroundColor: colors.sendRound,
      borderColor: 'transparent',
    },
    keyboardSendActionButtonText: {
      color: '#ffffff',
      fontWeight: '700',
    },
    keyboardActionButtonDisabled: {
      backgroundColor: colors.roundDisabled,
      borderColor: 'transparent',
      opacity: 0.72,
    },
    roundButton: {
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: colors.roundBorder,
      ...fabShadow,
    },
    micRoundButton: {
      backgroundColor: colors.micRound,
    },
    recordingRoundButton: {
      backgroundColor: colors.recordingRound,
      ...recordingFabShadow,
    },
    sendRoundButton: {
      backgroundColor: colors.sendRound,
    },
    roundButtonDisabled: {
      backgroundColor: colors.roundDisabled,
      shadowOpacity: 0,
      elevation: 0,
    },
    bottomActionButtonPressed: {
      transform: [{ scale: 0.95 }],
      opacity: 0.92,
    },
    quickTextButton: {
      width: 52,
      height: 52,
      borderRadius: 26,
      borderWidth: 1.5,
      borderColor: colors.quickActionBorder,
      backgroundColor: colors.quickActionBg,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
      ...quickFabShadow,
    },
    quickTextButtonSlot: {
      width: 52,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    quickTextButtonDisabled: {
      opacity: 0.42,
      shadowOpacity: 0,
      elevation: 0,
    },
    quickTextButtonIcon: {
      color: colors.quickActionText,
    },
    quickTextTooltip: {
      position: 'absolute',
      bottom: 60,
      minWidth: 88,
      maxWidth: 180,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.quickTooltipBorder,
      backgroundColor: colors.quickTooltipBg,
      paddingHorizontal: 10,
      paddingVertical: 6,
      zIndex: 3,
      ...surfaceShadow,
    },
    quickTextTooltipText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.quickTooltipText,
      textAlign: 'center',
    },
    bottomStateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      minHeight: 18,
      paddingHorizontal: 8,
      width: '100%',
    },
    bottomStateDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.bottomStateNeutral,
      flexShrink: 0,
    },
    bottomStateDotConnecting: {
      backgroundColor: colors.bottomStateConnecting,
    },
    bottomStateDotDisconnected: {
      backgroundColor: colors.bottomStateDisconnected,
    },
    bottomStateDotRecording: {
      backgroundColor: colors.bottomStateRecording,
    },
    bottomStateDotSending: {
      backgroundColor: colors.bottomStateSending,
    },
    bottomStateDotRetrying: {
      backgroundColor: colors.bottomStateRetrying,
    },
    bottomStateDotComplete: {
      backgroundColor: colors.bottomStateComplete,
    },
    bottomStateDotError: {
      backgroundColor: colors.bottomStateError,
    },
    bottomStateLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.bottomStateNeutral,
    },
    bottomStateLabelConnecting: {
      color: colors.bottomStateConnecting,
    },
    bottomStateLabelDisconnected: {
      color: colors.bottomStateDisconnected,
    },
    bottomStateLabelRecording: {
      color: colors.bottomStateRecording,
    },
    bottomStateLabelSending: {
      color: colors.bottomStateSending,
    },
    bottomStateLabelRetrying: {
      color: colors.bottomStateRetrying,
    },
    bottomStateLabelComplete: {
      color: colors.bottomStateComplete,
    },
    bottomStateLabelError: {
      color: colors.bottomStateError,
    },
    bottomStateDetail: {
      fontSize: 12,
      color: colors.bottomStateDetail,
      flexShrink: 1,
    },
  });
}
