import { StatusBar } from 'expo-status-bar';
import { useCallback, useEffect, useMemo } from 'react';
import {
  Keyboard,
  KeyboardAvoidingView,
  LogBox,
  Platform,
  SafeAreaView,
  View,
} from 'react-native';
import {
  ExpoSpeechRecognitionModule,
} from 'expo-speech-recognition';
import {
  setStorage,
  type Storage as OpenClawStorage,
} from './src/openclaw';
import {
  STORAGE_KEYS,
  OPENCLAW_IDENTITY_STORAGE_KEY,
} from './src/types';

// Import extracted constants
import {
  ENABLE_DEBUG_WARNINGS,
  DEFAULTS,
  TIMINGS,
  UI,
  MESSAGES,
  // Legacy exports for backward compatibility
  DEFAULT_GATEWAY_URL,
  DEFAULT_THEME,
  DEFAULT_SPEECH_LANG,
  DEFAULT_SESSION_KEY,
  DEFAULT_QUICK_TEXT_LEFT,
  DEFAULT_QUICK_TEXT_RIGHT,
  DEFAULT_QUICK_TEXT_LEFT_ICON,
  DEFAULT_QUICK_TEXT_RIGHT_ICON,
  getKvStore,
  MAX_TEXT_SCALE,
  MAX_TEXT_SCALE_TIGHT,
  HISTORY_BOTTOM_THRESHOLD_PX,
  ONBOARDING_SAMPLE_MESSAGE,
} from './src/utils';

// Import extracted helpers
import {
  dedupeLines,
  getTextOverlapSize,
  isMacDesktopRuntime,
  supportsSpeechRecognitionOnCurrentPlatform,
} from './src/utils';
import { useGatewayRuntime } from './src/ios-runtime/useGatewayRuntime';
import { useHistoryRuntime } from './src/ios-runtime/useHistoryRuntime';
import { useComposerRuntime } from './src/ios-runtime/useComposerRuntime';
import { useAppRuntimeState } from './src/ios-runtime/useAppRuntimeState';
import { useGatewayActionHandlers } from './src/ios-runtime/useGatewayActionHandlers';
import { useAppViewModel } from './src/ios-runtime/useAppViewModel';
import { useAppRuntimeOrchestrator } from './src/ios-runtime/useAppRuntimeOrchestrator';
import { useHomeUiState } from './src/ios-runtime/useHomeUiState';
import { useAppLifecycleRuntime } from './src/ios-runtime/useAppLifecycleRuntime';
import { useSettingsUiRuntime } from './src/ios-runtime/useSettingsUiRuntime';
import { useKeyboardUiRuntime } from './src/ios-runtime/useKeyboardUiRuntime';
import {
  useRuntimePersistenceEffects,
  useRuntimeUiEffects,
} from './src/ios-runtime/useAppRuntimeEffects';
import { useRuntimeUiHelpers } from './src/ios-runtime/useRuntimeUiHelpers';
import {
  formatClockLabel,
  formatSessionUpdatedAt,
  getHistoryDayKey,
  getHistoryDayLabel,
  isTurnWaitingState,
  normalizeQuickTextIcon,
  parseOutboxQueue,
  parseSessionPreferences,
} from './src/ios-runtime/app-runtime-pure';
import ConnectionHeader from './src/ui/ios/ConnectionHeader';
import SettingsScreenModal from './src/ui/ios/SettingsScreenModal';
import SessionsScreenModal from './src/ui/ios/SessionsScreenModal';
import SettingsPanelContent from './src/ui/ios/SettingsPanelContent';
import SessionsPanelContent from './src/ui/ios/SessionsPanelContent';
import HomeMainLayout from './src/ui/ios/HomeMainLayout';
import { createStyles } from './src/ui/ios/styles';

// Import contexts
import {
  ThemeProvider,
  useTheme,
  SettingsProvider,
  useSettings,
  GatewayProvider,
  useGateway,
} from './src/contexts';

if (__DEV__ && !ENABLE_DEBUG_WARNINGS) {
  LogBox.ignoreAllLogs(true);
}

const kvStore = getKvStore();
const openClawIdentityMemory = new Map<string, string>();

const openClawStorage: OpenClawStorage = {
  getString(key) {
    return openClawIdentityMemory.get(key);
  },
  set(key, value) {
    openClawIdentityMemory.set(key, value);
    void kvStore.setItemAsync(key, value).catch(() => {
      // ignore persistence errors
    });
  },
};

setStorage(openClawStorage);

function AppContent() {
  // Settings are now managed by SettingsContext
  const {
    gatewayUrl,
    setGatewayUrl,
    authToken,
    setAuthToken,
    speechLang,
    setSpeechLang,
    quickTextLeft,
    setQuickTextLeft,
    quickTextRight,
    setQuickTextRight,
    quickTextLeftIcon,
    setQuickTextLeftIcon,
    quickTextRightIcon,
    setQuickTextRightIcon,
    isOnboardingCompleted,
    setOnboardingCompleted: setIsOnboardingCompleted,
    isReady: settingsReady,
    isSaving: isSettingsSaving,
    pendingSaveCount: settingsPendingSaveCount,
    lastSavedAt: settingsLastSavedAt,
    saveError: settingsSaveError,
  } = useSettings();
  const {
    checkHealth: gatewayCheckHealth,
    refreshSessions: gatewayRefreshSessions,
    chatHistory: gatewayChatHistory,
    chatSend: gatewayChatSend,
    patchSession: gatewayPatchSession,
    connectionState: gatewayConnectionState,
    connectDiagnostic: gatewayConnectDiagnostic,
    sessions: gatewaySessions,
    isSessionsLoading: gatewaySessionsLoading,
    sessionsError: gatewaySessionsError,
  } = useGateway();

  const {
    state: gatewayRuntime,
    runAction: runGatewayRuntimeAction,
    setGatewayEventState,
    setIsSending,
    setIsSessionHistoryLoading,
    setIsMissingResponseRecoveryInFlight,
  } = useGatewayRuntime();
  const connectionState = gatewayConnectionState;
  const gatewayEventState = gatewayRuntime.gatewayEventState;
  const isSending = gatewayRuntime.isSending;
  const isSessionHistoryLoading = gatewayRuntime.isSessionHistoryLoading;
  const isMissingResponseRecoveryInFlight =
    gatewayRuntime.isMissingResponseRecoveryInFlight;
  const {
    composerHeight,
    setComposerHeight,
    setKeyboardState,
    isKeyboardVisible,
    historyBottomInset,
  } = useComposerRuntime();
  const { runHistoryRefresh, invalidateRefreshEpoch } = useHistoryRuntime();
  const {
    isAuthTokenMasked,
    setIsAuthTokenMasked,
    isSettingsPanelOpen,
    setIsSettingsPanelOpen,
    isSessionPanelOpen,
    setIsSessionPanelOpen,
    gatewayError,
    setGatewayError,
    activeRunId,
    setActiveRunId,
    chatTurns,
    setChatTurns,
    activeSessionKey,
    setActiveSessionKey,
    sessions,
    setSessions,
    sessionPreferences,
    setSessionPreferences,
    isSessionOperationPending,
    setIsSessionOperationPending,
    isSessionRenameOpen,
    setIsSessionRenameOpen,
    sessionRenameTargetKey,
    setSessionRenameTargetKey,
    sessionRenameDraft,
    setSessionRenameDraft,
    isStartupAutoConnecting,
    setIsStartupAutoConnecting,
    isOnboardingWaitingForResponse,
    setIsOnboardingWaitingForResponse,
    sessionsError,
    setSessionsError,
    historyLastSyncedAt,
    setHistoryLastSyncedAt,
    historyRefreshNotice,
    setHistoryRefreshNotice,
    missingResponseNotice,
    setMissingResponseNotice,
    showScrollToBottomButton,
    setShowScrollToBottomButton,
    outboxQueue,
    setOutboxQueue,
    quickTextTooltipSide,
    setQuickTextTooltipSide,
    focusedField,
    setFocusedField,
    isKeyboardBarMounted,
    setIsKeyboardBarMounted,
    isBottomCompletePulse,
    setIsBottomCompletePulse,
    isRecognizing,
    setIsRecognizing,
    transcript,
    setTranscript,
    interimTranscript,
    setInterimTranscript,
    speechError,
    setSpeechError,
    localStateReady,
    setLocalStateReady,
    activeSessionKeyRef,
    activeRunIdRef,
    pendingTurnIdRef,
    runIdToTurnIdRef,
    sessionTurnsRef,
    subscriptionsRef,
    transcriptRef,
    interimTranscriptRef,
    historyScrollRef,
    historyAutoScrollRef,
    historySyncTimerRef,
    historySyncRequestRef,
    missingResponseRecoveryTimerRef,
    missingResponseRecoveryRequestRef,
    historyNoticeTimerRef,
    bottomCompletePulseTimerRef,
    authTokenMaskTimerRef,
    outboxRetryTimerRef,
    outboxProcessingRef,
    outboxQueueRef,
    gatewayEventStateRef,
    gatewayUrlRef,
    connectionStateRef,
    startupAutoConnectRetryTimerRef,
    startupAutoConnectAttemptRef,
    finalResponseRecoveryTimerRef,
    sendFingerprintRef,
    holdStartTimerRef,
    holdActivatedRef,
    expectedSpeechStopRef,
    isUnmountingRef,
    startupAutoConnectAttemptedRef,
  } = useAppRuntimeState({
    defaultSessionKey: DEFAULT_SESSION_KEY,
    initialGatewayEventState: gatewayEventState,
    initialGatewayUrl: gatewayUrl,
    initialConnectionState: connectionState,
  });
  // Theme is now managed by ThemeContext
  const { theme, setTheme, isDark: isDarkTheme } = useTheme();

  const {
    settingsScrollRef,
    settingsFocusScrollTimerRef,
    quickTextTooltipTimerRef,
    quickTextLongPressResetTimerRef,
    quickTextInputRefs,
    quickTextLongPressSideRef,
    clearQuickTextLongPressResetTimer,
    hideQuickTextTooltip,
    scheduleQuickTextTooltipHide,
    ensureSettingsFieldVisible,
  } = useSettingsUiRuntime({
    setQuickTextTooltipSide,
  });

  const isGatewayConnected = connectionState === 'connected';
  const isGatewayConnecting =
    connectionState === 'connecting' || connectionState === 'reconnecting';
  const isMacRuntime = isMacDesktopRuntime();
  const shouldForceSettingsScreen = !isGatewayConnected && !isMacRuntime;
  const shouldShowSettingsScreen = shouldForceSettingsScreen || isSettingsPanelOpen;
  const canToggleSettingsPanel = isGatewayConnected || isMacRuntime;
  const canDismissSettingsScreen = isGatewayConnected || isMacRuntime;
  const isSessionsLoading = gatewaySessionsLoading;
  // isDarkTheme is now provided by useTheme()

  const {
    persistRuntimeSetting,
    clearHistoryNoticeTimer,
    clearBottomCompletePulseTimer,
    forceMaskAuthToken,
    toggleAuthTokenVisibility,
    clearOutboxRetryTimer,
    showHistoryRefreshNotice,
    clearStartupAutoConnectRetryTimer,
    clearFinalResponseRecoveryTimer,
    clearMissingResponseRecoveryTimer,
    clearMissingResponseRecoveryState,
    runGatewayHealthCheck,
    scrollHistoryToBottom,
  } = useRuntimeUiHelpers({
    historyNoticeTimerRef,
    bottomCompletePulseTimerRef,
    authTokenMaskTimerRef,
    outboxRetryTimerRef,
    startupAutoConnectRetryTimerRef,
    finalResponseRecoveryTimerRef,
    missingResponseRecoveryTimerRef,
    missingResponseRecoveryRequestRef,
    connectionStateRef,
    historyScrollRef,
    historyAutoScrollRef,
    gatewayCheckHealth,
    setIsAuthTokenMasked,
    setHistoryRefreshNotice,
    setShowScrollToBottomButton,
    setIsMissingResponseRecoveryInFlight,
    setMissingResponseNotice,
  });

  useRuntimeUiEffects({
    shouldShowSettingsScreen,
    forceMaskAuthToken,
    missingResponseNotice,
    activeSessionKey,
    chatTurns,
    clearMissingResponseRecoveryState,
    isTurnWaitingState,
    transcript,
    transcriptRef,
    interimTranscript,
    interimTranscriptRef,
    activeSessionKeyRef,
    historyAutoScrollRef,
    setShowScrollToBottomButton,
    gatewayUrl,
    gatewayUrlRef,
    connectionState,
    connectionStateRef,
    outboxQueue,
    outboxQueueRef,
    gatewaySessions,
    setSessions,
    gatewaySessionsError,
    setSessionsError,
    gatewayEventState,
    gatewayEventStateRef,
    isSending,
    setIsBottomCompletePulse,
    clearBottomCompletePulseTimer,
    bottomCompletePulseTimerRef,
    setGatewayEventState,
    sessionTurnsRef,
    scrollHistoryToBottom,
    isOnboardingCompleted,
    isOnboardingWaitingForResponse,
    setIsOnboardingCompleted,
    setIsOnboardingWaitingForResponse,
    isGatewayConnected,
    setIsSessionPanelOpen,
  });

  useRuntimePersistenceEffects({
    settingsReady,
    persistRuntimeSetting,
    activeSessionKey,
    sessionPreferences,
    outboxQueue,
    kvStore,
    sessionKeyStorageKey: STORAGE_KEYS.sessionKey,
    sessionPrefsStorageKey: STORAGE_KEYS.sessionPrefs,
    outboxQueueStorageKey: STORAGE_KEYS.outboxQueue,
    identityStorageKey: OPENCLAW_IDENTITY_STORAGE_KEY,
    openClawIdentityMemory,
    parseSessionPreferences,
    parseOutboxQueue,
    defaultSessionKey: DEFAULT_SESSION_KEY,
    activeSessionKeyRef,
    sessionTurnsRef,
    setActiveSessionKey,
    setSessionPreferences,
    setOutboxQueue,
    setGatewayEventState,
    setChatTurns,
    setLocalStateReady,
  });

  const {
    refreshSessions,
    loadSessionHistory,
    switchSession,
    createAndSwitchSession,
    isSessionPinned,
    getSessionTitle,
    startSessionRename,
    submitSessionRename,
    toggleSessionPinned,
    connectGateway,
    disconnectGateway,
    sendToGateway,
    startRecognition,
    stopRecognition,
    scheduleSessionHistorySync,
    scheduleMissingResponseRecovery,
    scheduleFinalResponseRecovery,
  } = useAppRuntimeOrchestrator({
    setChatTurns,
    sessionHistoryInput: {
      connectionState,
      connectionStateRef,
      isSending,
      isSessionOperationPending,
      activeSessionKeyRef,
      activeRunIdRef,
      pendingTurnIdRef,
      runIdToTurnIdRef,
      sessionTurnsRef,
      outboxQueueRef,
      gatewayRefreshSessions,
      gatewayChatHistory,
      runHistoryRefresh,
      runGatewayRuntimeAction,
      invalidateRefreshEpoch,
      setSessions,
      setSessionsError,
      setGatewayError,
      setChatTurns,
      setActiveSessionKey,
      setFocusedField,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
      setSessionRenameDraft,
      setIsSending,
      setGatewayEventState,
      setHistoryLastSyncedAt,
      setActiveRunId,
    },
    sessionActionsInput: {
      connectionState,
      isGatewayConnected,
      isSessionOperationPending,
      sessionRenameTargetKey,
      sessionRenameDraft,
      sessionPreferences,
      sessions,
      activeSessionKeyRef,
      gatewayPatchSession,
      setSessionsError,
      setIsSessionOperationPending,
      setSessionPreferences,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
      setSessionRenameDraft,
    },
    sessionRuntimeInput: {
      historySyncTimerRef,
      historySyncRequestRef,
      missingResponseRecoveryTimerRef,
      missingResponseRecoveryRequestRef,
      finalResponseRecoveryTimerRef,
      connectionStateRef,
      sessionTurnsRef,
      clearMissingResponseRecoveryTimer,
      clearFinalResponseRecoveryTimer,
      setIsMissingResponseRecoveryInFlight,
      setMissingResponseNotice,
      isTurnWaitingState,
    },
    gatewayEventBridgeInput: {
      activeSessionKeyRef,
      activeRunIdRef,
      pendingTurnIdRef,
      runIdToTurnIdRef,
      sessionTurnsRef,
      setGatewayEventState,
      setIsSending,
      setActiveRunId,
      isOnboardingWaitingForResponse,
      setIsOnboardingWaitingForResponse,
      setIsOnboardingCompleted,
      clearFinalResponseRecoveryTimer,
      clearMissingResponseRecoveryState,
      setGatewayError,
    },
    gatewayConnectionFlowInput: {
      gatewayUrl,
      authToken,
      settingsReady,
      gatewayUrlRef,
      connectionStateRef,
      isUnmountingRef,
      subscriptionsRef,
      historySyncTimerRef,
      historySyncRequestRef,
      outboxProcessingRef,
      startupAutoConnectAttemptRef,
      startupAutoConnectRetryTimerRef,
      activeRunIdRef,
      pendingTurnIdRef,
      runIdToTurnIdRef,
      setActiveRunId,
      setGatewayError,
      setSessionsError,
      setGatewayEventState,
      setIsSettingsPanelOpen,
      setIsStartupAutoConnecting,
      setIsSessionOperationPending,
      setIsBottomCompletePulse,
      clearFinalResponseRecoveryTimer,
      clearMissingResponseRecoveryState,
      clearStartupAutoConnectRetryTimer,
      clearBottomCompletePulseTimer,
      clearOutboxRetryTimer,
      invalidateRefreshEpoch,
      forceMaskAuthToken,
      runGatewayRuntimeAction,
    },
    outboxRuntimeInput: {
      isSending,
      connectionState,
      outboxQueue,
      outboxQueueRef,
      outboxProcessingRef,
      outboxRetryTimerRef,
      connectionStateRef,
      activeSessionKeyRef,
      transcriptRef,
      interimTranscriptRef,
      sendFingerprintRef,
      pendingTurnIdRef,
      activeRunIdRef,
      runIdToTurnIdRef,
      gatewaySendChat: gatewayChatSend,
      runGatewayHealthCheck,
      runGatewayRuntimeAction,
      clearOutboxRetryTimer,
      clearMissingResponseRecoveryState,
      setGatewayError,
      setGatewayEventState,
      setOutboxQueue,
      setChatTurns,
      setTranscript,
      setInterimTranscript,
      setActiveRunId,
    },
    speechRuntimeInput: {
      speechLang,
      isRecognizing,
      expectedSpeechStopRef,
      isUnmountingRef,
      setIsRecognizing,
      setSpeechError,
      setTranscript,
      setInterimTranscript,
    },
  });

  const abortSpeechRecognitionIfSupported = useCallback(() => {
    if (!supportsSpeechRecognitionOnCurrentPlatform()) return;
    ExpoSpeechRecognitionModule.abort();
  }, []);

  useAppLifecycleRuntime({
    localStateReady,
    settingsReady,
    gatewayUrl,
    connectionState,
    startupAutoConnectAttemptedRef,
    startupAutoConnectAttemptRef,
    connectGateway,
    isUnmountingRef,
    invalidateRefreshEpoch,
    expectedSpeechStopRef,
    holdStartTimerRef,
    historySyncTimerRef,
    historySyncRequestRef,
    historyNoticeTimerRef,
    bottomCompletePulseTimerRef,
    authTokenMaskTimerRef,
    outboxRetryTimerRef,
    startupAutoConnectRetryTimerRef,
    finalResponseRecoveryTimerRef,
    missingResponseRecoveryTimerRef,
    missingResponseRecoveryRequestRef,
    settingsFocusScrollTimerRef,
    quickTextTooltipTimerRef,
    quickTextLongPressResetTimerRef,
    quickTextLongPressSideRef,
    disconnectGateway,
    abortSpeechRecognitionIfSupported,
  });

  const {
    canSendDraft,
    quickTextLeftLabel,
    quickTextRightLabel,
    isTranscriptFocused,
    isQuickTextSettingsEditMode,
    showKeyboardActionBar,
    showDoneOnlyAction,
    showClearInKeyboardBar,
    canSendFromKeyboardBar,
    canClearFromKeyboardBar,
    speechRecognitionSupported,
    canUseQuickTextLeft,
    canUseQuickTextRight,
    showQuickTextLeftTooltip,
    showQuickTextRightTooltip,
    isTranscriptEditingWithKeyboard,
    isHomeComposingMode,
    showHistoryCard,
    showHistoryRefreshButton,
    transcriptPlaceholder,
    shouldUseCompactTranscriptCard,
    canSwitchSession,
    canRefreshSessions,
    canCreateSession,
    canRenameSession,
    canPinSession,
    visibleSessions,
    sessionPanelStatusText,
    sessionListHintText,
    settingsStatusText,
    isSettingsStatusError,
    isSettingsStatusPending,
    sectionIconColor,
    actionIconColor,
    currentBadgeIconColor,
    pinnedBadgeIconColor,
    optionIconColor,
    showOnboardingGuide,
    isOnboardingGatewayConfigured,
    isOnboardingConnectDone,
    isOnboardingResponseDone,
    canRunOnboardingConnectTest,
    canRunOnboardingSampleSend,
    onboardingSampleButtonLabel,
    showGatewayDiagnostic,
    gatewayDiagnosticIconName,
    activeMissingResponseNotice,
    canRetryMissingResponse,
    historyUpdatedLabel,
    showHistoryUpdatedMeta,
    historyListBottomPadding,
    bottomActionStatus,
    bottomActionDetailText,
    showBottomStatus,
    bottomActionStatusLabel,
    connectionStatusLabel,
    showHistoryDateDivider,
    showHistoryScrollButton,
    historyItems,
    latestRetryText,
    canReconnectFromError,
    canRetryFromError,
    topBannerKind,
    topBannerMessage,
    topBannerIconName,
  } = useHomeUiState({
    transcript,
    interimTranscript,
    isRecognizing,
    quickTextLeft,
    quickTextRight,
    focusedField,
    shouldShowSettingsScreen,
    isKeyboardVisible,
    isSending,
    settingsReady,
    isSessionOperationPending,
    isGatewayConnected,
    isSessionsLoading,
    sessions,
    sessionPreferences,
    sessionsError,
    isSettingsSaving,
    settingsPendingSaveCount,
    settingsSaveError,
    settingsLastSavedAt,
    isDarkTheme,
    isOnboardingCompleted,
    gatewayUrl,
    chatTurns,
    isGatewayConnecting,
    isOnboardingWaitingForResponse,
    gatewayConnectDiagnostic,
    outboxQueueLength: outboxQueue.length,
    missingResponseNotice,
    activeSessionKey,
    isMissingResponseRecoveryInFlight,
    historyRefreshNotice,
    historyLastSyncedAt,
    historyBottomInset,
    showScrollToBottomButton,
    gatewayError,
    speechError,
    gatewayEventState,
    connectionState,
    isStartupAutoConnecting,
    isBottomCompletePulse,
    isKeyboardBarMounted,
    formatClockLabel,
    getHistoryDayKey,
    getHistoryDayLabel,
    quickTextTooltipSide,
  });
  const {
    handleReconnectFromError,
    handleRetryFromError,
    handleRetryMissingResponse,
    handleDismissTopBanner,
    handleCompleteOnboarding,
    handleOnboardingConnectTest,
    handleOnboardingSendSample,
    handleToggleSessionPanel,
    handleToggleSettingsPanel,
    handleCloseSettingsPanel,
    handleCloseSessionPanel,
    handleDoneKeyboardAction,
    handleClearKeyboardAction,
    handleSendKeyboardAction,
    handleSendDraftAction,
    handleTranscriptChange,
    handleTranscriptFocus,
    handleTranscriptBlur,
    handleRefreshHistory,
    handleScrollHistoryToBottom,
    handleHoldToTalkPressIn,
    handleHoldToTalkPressOut,
    handleHistoryScroll,
    handleHistoryAutoScroll,
    handleHistoryLayoutAutoScroll,
    handleBottomDockHeightChange,
    handleBottomDockActionPressHaptic,
    handleQuickTextLongPress,
    handleQuickTextPress,
    handleQuickTextPressOut,
  } = useGatewayActionHandlers({
    homeUiInput: {
      canReconnectFromError,
      canRetryFromError,
      latestRetryText,
      connectGateway,
      sendToGateway,
      setFocusedField,
      activeMissingResponseNotice,
      isMissingResponseRecoveryInFlight,
      isGatewayConnected,
      setGatewayError,
      scheduleMissingResponseRecovery,
      topBannerKind,
      setMissingResponseNotice,
      setHistoryRefreshNotice,
      setSpeechError,
      setIsOnboardingWaitingForResponse,
      setIsOnboardingCompleted,
      canRunOnboardingConnectTest,
      canRunOnboardingSampleSend,
      onboardingSampleMessage: ONBOARDING_SAMPLE_MESSAGE,
      forceMaskAuthToken,
      isSessionPanelOpen,
      refreshSessions,
      setIsSettingsPanelOpen,
      setIsSessionPanelOpen,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
      setSessionRenameDraft,
      canToggleSettingsPanel,
      canDismissSettingsScreen,
      canClearFromKeyboardBar,
      canSendFromKeyboardBar,
      transcript,
      interimTranscript,
      setTranscript,
      setInterimTranscript,
      isSessionHistoryLoading,
      clearHistoryNoticeTimer,
      activeSessionKeyRef,
      loadSessionHistory,
      setHistoryLastSyncedAt,
      showHistoryRefreshNotice,
      formatClockLabel,
      scrollHistoryToBottom,
      historyAutoScrollRef,
      setShowScrollToBottomButton,
      chatTurnsLength: chatTurns.length,
      historyBottomThresholdPx: HISTORY_BOTTOM_THRESHOLD_PX,
      speechRecognitionSupported,
      isRecognizing,
      isSending,
      holdActivatedRef,
      holdStartTimerRef,
      startRecognition,
      stopRecognition,
      composerHeight,
      setComposerHeight,
    },
    quickTextInput: {
      isRecognizing,
      setTranscript,
      setInterimTranscript,
      setQuickTextTooltipSide,
      clearQuickTextLongPressResetTimer,
      scheduleQuickTextTooltipHide,
      hideQuickTextTooltip,
      quickTextLongPressSideRef,
      quickTextLongPressResetTimerRef,
    },
    transcriptRef,
    interimTranscriptRef,
    setTranscript,
    setInterimTranscript,
    setSpeechError,
  });

  const styles = useMemo(() => createStyles(isDarkTheme), [isDarkTheme]);
  const placeholderColor = isDarkTheme ? '#95a8ca' : '#C4C4C0';

  const { keyboardBarAnim } = useKeyboardUiRuntime({
    showKeyboardActionBar,
    setKeyboardState,
    setIsKeyboardBarMounted,
  });

  const {
    connectionHeaderProps,
    settingsScreenModalProps,
    settingsPanelContentProps,
    sessionsScreenModalProps,
    sessionsPanelContentProps,
    homeMainLayoutProps,
  } = useAppViewModel({
    styles,
    isDarkTheme,
    maxTextScale: MAX_TEXT_SCALE,
    maxTextScaleTight: MAX_TEXT_SCALE_TIGHT,
    placeholderColor,
    connectionHeader: {
      connectionLabel: connectionStatusLabel,
      isGatewayConnected,
      isGatewayConnecting,
      isSessionPanelOpen,
      isSettingsPanelOpen,
      canToggleSettingsPanel,
      onToggleSessionPanel: handleToggleSessionPanel,
      onToggleSettingsPanel: handleToggleSettingsPanel,
    },
    settingsScreenModal: {
      visible: shouldShowSettingsScreen,
      canDismissSettingsScreen,
      isSettingsStatusPending,
      isSettingsStatusError,
      settingsStatusText,
      isKeyboardVisible,
      settingsScrollRef,
      onClose: handleCloseSettingsPanel,
    },
    settingsPanelContent: {
      showOnboardingGuide,
      isQuickTextSettingsEditMode,
      sectionIconColor,
      currentBadgeIconColor,
      optionIconColor,
      actionIconColor,
      isOnboardingGatewayConfigured,
      isOnboardingConnectDone,
      isOnboardingResponseDone,
      isOnboardingWaitingForResponse,
      canRunOnboardingConnectTest,
      canRunOnboardingSampleSend,
      isGatewayConnecting,
      onboardingSampleButtonLabel,
      onOnboardingConnectTest: handleOnboardingConnectTest,
      onOnboardingSendSample: handleOnboardingSendSample,
      onCompleteOnboarding: handleCompleteOnboarding,
      focusedField,
      setFocusedField,
      gatewayUrl,
      setGatewayUrl,
      authToken,
      setAuthToken,
      isAuthTokenMasked,
      toggleAuthTokenVisibility,
      settingsReady,
      connectGateway,
      isStartupAutoConnecting,
      showGatewayDiagnostic,
      gatewayDiagnosticIconName,
      gatewayConnectDiagnostic,
      theme,
      setTheme,
      speechLang,
      setSpeechLang,
      quickTextInputRefs,
      quickTextLeft,
      setQuickTextLeft,
      quickTextRight,
      setQuickTextRight,
      quickTextLeftIcon,
      setQuickTextLeftIcon,
      quickTextRightIcon,
      setQuickTextRightIcon,
      ensureSettingsFieldVisible,
      enableDebugWarnings: ENABLE_DEBUG_WARNINGS,
      connectionState,
      gatewayEventState,
      activeSessionKey,
      activeRunId,
      historyLastSyncedAt,
      startupAutoConnectAttempt: startupAutoConnectAttemptRef.current,
    },
    sessionsScreenModal: {
      visible: isGatewayConnected && isSessionPanelOpen,
      isSessionsLoading,
      hasSessionsError: Boolean(sessionsError),
      sessionPanelStatusText,
      onClose: handleCloseSessionPanel,
    },
    sessionsPanelContent: {
      sectionIconColor,
      actionIconColor,
      currentBadgeIconColor,
      pinnedBadgeIconColor,
      isGatewayConnected,
      canRefreshSessions,
      canCreateSession,
      canSwitchSession,
      canRenameSession,
      canPinSession,
      activeSessionKey,
      visibleSessions,
      sessionRenameTargetKey,
      isSessionRenameOpen,
      sessionRenameDraft,
      setSessionRenameDraft,
      isSessionOperationPending,
      sessionsError,
      sessionListHintText,
      refreshSessions,
      createAndSwitchSession,
      switchSession,
      isSessionPinned,
      getSessionTitle,
      formatSessionUpdatedAt,
      startSessionRename,
      toggleSessionPinned,
      submitSessionRename,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
    },
    homeMainLayout: {
      topBannerKind,
      topBannerMessage: topBannerMessage ?? null,
      topBannerIconName,
      canReconnectFromError,
      canRetryFromError,
      canRetryMissingResponse,
      isMissingResponseRecoveryInFlight,
      isGatewayConnected,
      onReconnectFromError: handleReconnectFromError,
      onRetryFromError: handleRetryFromError,
      onRetryMissingResponse: handleRetryMissingResponse,
      onDismissTopBanner: handleDismissTopBanner,
      showHistoryCard,
      showHistoryRefreshButton,
      isSessionHistoryLoading,
      onRefreshHistory: handleRefreshHistory,
      showHistoryUpdatedMeta,
      historyUpdatedLabel,
      historyScrollRef,
      historyItems,
      historyListBottomPadding,
      showScrollToBottomButton,
      showHistoryScrollButton,
      isHomeComposingMode,
      showHistoryDateDivider,
      onHistoryScroll: handleHistoryScroll,
      onHistoryAutoScroll: handleHistoryAutoScroll,
      onHistoryLayoutAutoScroll: handleHistoryLayoutAutoScroll,
      onScrollHistoryToBottom: handleScrollHistoryToBottom,
      isRecognizing,
      isTranscriptEditingWithKeyboard,
      shouldUseCompactTranscriptCard,
      focusedField,
      transcript,
      transcriptPlaceholder,
      interimTranscript,
      onTranscriptChange: handleTranscriptChange,
      onFocusTranscript: handleTranscriptFocus,
      onBlurTranscript: handleTranscriptBlur,
      isTranscriptFocused,
      isKeyboardVisible,
      onBottomDockHeightChange: handleBottomDockHeightChange,
      isKeyboardBarMounted,
      keyboardBarAnim,
      showDoneOnlyAction,
      showClearInKeyboardBar,
      canClearFromKeyboardBar,
      canSendFromKeyboardBar,
      onDoneKeyboardAction: handleDoneKeyboardAction,
      onClearKeyboardAction: handleClearKeyboardAction,
      onSendKeyboardAction: handleSendKeyboardAction,
      showQuickTextLeftTooltip,
      showQuickTextRightTooltip,
      quickTextLeftLabel,
      quickTextRightLabel,
      quickTextLeftIcon,
      quickTextRightIcon,
      canUseQuickTextLeft,
      canUseQuickTextRight,
      onQuickTextPress: handleQuickTextPress,
      onQuickTextLongPress: handleQuickTextLongPress,
      onQuickTextPressOut: handleQuickTextPressOut,
      canSendDraft,
      isSending,
      speechRecognitionSupported,
      settingsReady,
      onSendDraftAction: handleSendDraftAction,
      onMicPressIn: handleHoldToTalkPressIn,
      onMicPressOut: handleHoldToTalkPressOut,
      onActionPressHaptic: handleBottomDockActionPressHaptic,
      showBottomStatus,
      bottomActionStatus,
      bottomActionLabel: bottomActionStatusLabel,
      bottomActionDetailText,
    },
  });

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar style={isDarkTheme ? 'light' : 'dark'} />
      <KeyboardAvoidingView
        style={styles.keyboardWrap}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ConnectionHeader {...connectionHeaderProps} />

        <SettingsScreenModal {...settingsScreenModalProps}>
          <SettingsPanelContent {...settingsPanelContentProps} />
        </SettingsScreenModal>
        <SessionsScreenModal {...sessionsScreenModalProps}>
          <SessionsPanelContent {...sessionsPanelContentProps} />
        </SessionsScreenModal>
        <HomeMainLayout {...homeMainLayoutProps} />
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

/**
 * Root App component with Providers
 */
export default function App() {
  return (
    <ThemeProvider>
      <SettingsProvider>
        <GatewayProvider>
          <AppContent />
        </GatewayProvider>
      </SettingsProvider>
    </ThemeProvider>
  );
}
