import { useTheme, useSettings, useGateway } from '../contexts';
import {
  OPENCLAW_IDENTITY_STORAGE_KEY,
  STORAGE_KEYS,
} from '../types';
import {
  getKvStore,
  DEFAULT_SESSION_KEY,
  isMacDesktopRuntime,
} from '../utils';
import { useGatewayRuntime } from './useGatewayRuntime';
import { useHistoryRuntime } from './useHistoryRuntime';
import { useComposerRuntime } from './useComposerRuntime';
import { useAppRuntimeState } from './useAppRuntimeState';
import { useAppRuntimeOrchestrator } from './useAppRuntimeOrchestrator';
import { useAppContentWiring } from './useAppContentWiring';
import { useAppViewModelWiring } from './useAppViewModelWiring';
import { useSettingsUiRuntime } from './useSettingsUiRuntime';
import { useKeyboardUiRuntime } from './useKeyboardUiRuntime';
import { useAppRuntimeSideEffects } from './useAppRuntimeSideEffects';
import { useRuntimeUiHelpers } from './useRuntimeUiHelpers';
import {
  formatClockLabel,
  formatSessionUpdatedAt,
  getHistoryDayKey,
  getHistoryDayLabel,
  isTurnWaitingState,
  parseOutboxQueue,
  parseSessionPreferences,
} from './app-runtime-pure';

type UseAppScreenWiringInput = {
  kvStore: ReturnType<typeof getKvStore>;
  openClawIdentityMemory: Map<string, string>;
};

export function useAppScreenWiring(input: UseAppScreenWiringInput) {
  const settings = useSettings();
  const gateway = useGateway();

  const {
    state: gatewayRuntime,
    runAction: runGatewayRuntimeAction,
    setGatewayEventState,
    setIsSending,
    setIsSessionHistoryLoading,
    setIsMissingResponseRecoveryInFlight,
  } = useGatewayRuntime();
  const connectionState = gateway.connectionState;
  const gatewayEventState = gatewayRuntime.gatewayEventState;
  const isSending = gatewayRuntime.isSending;
  const isSessionHistoryLoading = gatewayRuntime.isSessionHistoryLoading;
  const isMissingResponseRecoveryInFlight =
    gatewayRuntime.isMissingResponseRecoveryInFlight;

  const {
    composerHeight,
    setComposerHeight,
    setKeyboardState,
    isKeyboardVisible,
    historyBottomInset,
  } = useComposerRuntime();
  const { runHistoryRefresh, invalidateRefreshEpoch } = useHistoryRuntime();

  const appState = useAppRuntimeState({
    defaultSessionKey: DEFAULT_SESSION_KEY,
    initialGatewayEventState: gatewayEventState,
    initialGatewayUrl: settings.gatewayUrl,
    initialConnectionState: connectionState,
  });
  const runtimeRefs = appState;

  const {
    isAuthTokenMasked,
    setIsAuthTokenMasked,
    isSettingsPanelOpen,
    setIsSettingsPanelOpen,
    isSessionPanelOpen,
    setIsSessionPanelOpen,
    gatewayError,
    setGatewayError,
    activeRunId,
    setActiveRunId,
    chatTurns,
    setChatTurns,
    activeSessionKey,
    setActiveSessionKey,
    sessions,
    setSessions,
    sessionPreferences,
    setSessionPreferences,
    isSessionOperationPending,
    setIsSessionOperationPending,
    isSessionRenameOpen,
    setIsSessionRenameOpen,
    sessionRenameTargetKey,
    setSessionRenameTargetKey,
    sessionRenameDraft,
    setSessionRenameDraft,
    isStartupAutoConnecting,
    setIsStartupAutoConnecting,
    isOnboardingWaitingForResponse,
    setIsOnboardingWaitingForResponse,
    sessionsError,
    setSessionsError,
    historyLastSyncedAt,
    setHistoryLastSyncedAt,
    historyRefreshNotice,
    setHistoryRefreshNotice,
    missingResponseNotice,
    setMissingResponseNotice,
    showScrollToBottomButton,
    setShowScrollToBottomButton,
    outboxQueue,
    setOutboxQueue,
    quickTextTooltipSide,
    setQuickTextTooltipSide,
    focusedField,
    setFocusedField,
    isKeyboardBarMounted,
    setIsKeyboardBarMounted,
    isBottomCompletePulse,
    setIsBottomCompletePulse,
    isRecognizing,
    setIsRecognizing,
    transcript,
    setTranscript,
    interimTranscript,
    setInterimTranscript,
    speechError,
    setSpeechError,
    localStateReady,
    setLocalStateReady,
  } = appState;

  const setIsOnboardingCompleted = settings.setOnboardingCompleted;
  const settingsReady = settings.isReady;
  const isSettingsSaving = settings.isSaving;
  const settingsPendingSaveCount = settings.pendingSaveCount;
  const settingsLastSavedAt = settings.lastSavedAt;
  const settingsSaveError = settings.saveError;

  const {
    gatewayUrl,
    setGatewayUrl,
    authToken,
    setAuthToken,
    speechLang,
    setSpeechLang,
    quickTextLeft,
    setQuickTextLeft,
    quickTextRight,
    setQuickTextRight,
    quickTextLeftIcon,
    setQuickTextLeftIcon,
    quickTextRightIcon,
    setQuickTextRightIcon,
    isOnboardingCompleted,
  } = settings;

  const {
    connectDiagnostic: gatewayConnectDiagnostic,
    sessions: gatewaySessions,
    sessionsError: gatewaySessionsError,
    checkHealth: gatewayCheckHealth,
    refreshSessions: gatewayRefreshSessions,
    chatHistory: gatewayChatHistory,
    patchSession: gatewayPatchSession,
    chatSend: gatewayChatSend,
  } = gateway;

  const {
    activeSessionKeyRef,
    activeRunIdRef,
    pendingTurnIdRef,
    runIdToTurnIdRef,
    sessionTurnsRef,
    subscriptionsRef,
    transcriptRef,
    interimTranscriptRef,
    historyScrollRef,
    historyAutoScrollRef,
    historySyncTimerRef,
    historySyncRequestRef,
    missingResponseRecoveryTimerRef,
    missingResponseRecoveryRequestRef,
    historyNoticeTimerRef,
    bottomCompletePulseTimerRef,
    authTokenMaskTimerRef,
    outboxRetryTimerRef,
    outboxProcessingRef,
    outboxQueueRef,
    gatewayEventStateRef,
    gatewayUrlRef,
    connectionStateRef,
    startupAutoConnectRetryTimerRef,
    startupAutoConnectAttemptRef,
    finalResponseRecoveryTimerRef,
    sendFingerprintRef,
    holdStartTimerRef,
    holdActivatedRef,
    expectedSpeechStopRef,
    isUnmountingRef,
    startupAutoConnectAttemptedRef,
  } = runtimeRefs;

  const { theme, setTheme, isDark: isDarkTheme } = useTheme();

  const {
    settingsScrollRef,
    settingsFocusScrollTimerRef,
    quickTextTooltipTimerRef,
    quickTextLongPressResetTimerRef,
    quickTextInputRefs,
    quickTextLongPressSideRef,
    clearQuickTextLongPressResetTimer,
    hideQuickTextTooltip,
    scheduleQuickTextTooltipHide,
    ensureSettingsFieldVisible,
  } = useSettingsUiRuntime({
    setQuickTextTooltipSide,
  });

  const isGatewayConnected = connectionState === 'connected';
  const isGatewayConnecting =
    connectionState === 'connecting' || connectionState === 'reconnecting';
  const isMacRuntime = isMacDesktopRuntime();
  const shouldForceSettingsScreen = !isGatewayConnected && !isMacRuntime;
  const shouldShowSettingsScreen = shouldForceSettingsScreen || isSettingsPanelOpen;
  const canToggleSettingsPanel = isGatewayConnected || isMacRuntime;
  const canDismissSettingsScreen = isGatewayConnected || isMacRuntime;
  const isSessionsLoading = gateway.isSessionsLoading;

  const {
    persistRuntimeSetting,
    clearHistoryNoticeTimer,
    clearBottomCompletePulseTimer,
    forceMaskAuthToken,
    toggleAuthTokenVisibility,
    clearOutboxRetryTimer,
    showHistoryRefreshNotice,
    clearStartupAutoConnectRetryTimer,
    clearFinalResponseRecoveryTimer,
    clearMissingResponseRecoveryTimer,
    clearMissingResponseRecoveryState,
    runGatewayHealthCheck,
    scrollHistoryToBottom,
  } = useRuntimeUiHelpers({
    historyNoticeTimerRef,
    bottomCompletePulseTimerRef,
    authTokenMaskTimerRef,
    outboxRetryTimerRef,
    startupAutoConnectRetryTimerRef,
    finalResponseRecoveryTimerRef,
    missingResponseRecoveryTimerRef,
    missingResponseRecoveryRequestRef,
    connectionStateRef,
    historyScrollRef,
    historyAutoScrollRef,
    gatewayCheckHealth,
    setIsAuthTokenMasked,
    setHistoryRefreshNotice,
    setShowScrollToBottomButton,
    setIsMissingResponseRecoveryInFlight,
    setMissingResponseNotice,
  });

  const {
    refreshSessions,
    loadSessionHistory,
    switchSession,
    createAndSwitchSession,
    isSessionPinned,
    getSessionTitle,
    startSessionRename,
    submitSessionRename,
    toggleSessionPinned,
    connectGateway,
    disconnectGateway,
    sendToGateway,
    startRecognition,
    stopRecognition,
    scheduleSessionHistorySync,
    scheduleMissingResponseRecovery,
    scheduleFinalResponseRecovery,
  } = useAppRuntimeOrchestrator({
    setChatTurns,
    sessionHistoryInput: {
      connectionState,
      connectionStateRef,
      isSending,
      isSessionOperationPending,
      activeSessionKeyRef,
      activeRunIdRef,
      pendingTurnIdRef,
      runIdToTurnIdRef,
      sessionTurnsRef,
      outboxQueueRef,
      gatewayRefreshSessions,
      gatewayChatHistory,
      runHistoryRefresh,
      runGatewayRuntimeAction,
      invalidateRefreshEpoch,
      setSessions,
      setSessionsError,
      setGatewayError,
      setChatTurns,
      setActiveSessionKey,
      setFocusedField,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
      setSessionRenameDraft,
      setIsSending,
      setGatewayEventState,
      setHistoryLastSyncedAt,
      setActiveRunId,
    },
    sessionActionsInput: {
      connectionState,
      isGatewayConnected,
      isSessionOperationPending,
      sessionRenameTargetKey,
      sessionRenameDraft,
      sessionPreferences,
      sessions,
      activeSessionKeyRef,
      gatewayPatchSession,
      setSessionsError,
      setIsSessionOperationPending,
      setSessionPreferences,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
      setSessionRenameDraft,
    },
    sessionRuntimeInput: {
      historySyncTimerRef,
      historySyncRequestRef,
      missingResponseRecoveryTimerRef,
      missingResponseRecoveryRequestRef,
      finalResponseRecoveryTimerRef,
      connectionStateRef,
      sessionTurnsRef,
      clearMissingResponseRecoveryTimer,
      clearFinalResponseRecoveryTimer,
      setIsMissingResponseRecoveryInFlight,
      setMissingResponseNotice,
      isTurnWaitingState,
    },
    gatewayEventBridgeInput: {
      activeSessionKeyRef,
      activeRunIdRef,
      pendingTurnIdRef,
      runIdToTurnIdRef,
      sessionTurnsRef,
      setGatewayEventState,
      setIsSending,
      setActiveRunId,
      isOnboardingWaitingForResponse,
      setIsOnboardingWaitingForResponse,
      setIsOnboardingCompleted,
      clearFinalResponseRecoveryTimer,
      clearMissingResponseRecoveryState,
      setGatewayError,
    },
    gatewayConnectionFlowInput: {
      gatewayUrl,
      authToken,
      settingsReady,
      gatewayUrlRef,
      connectionStateRef,
      isUnmountingRef,
      subscriptionsRef,
      historySyncTimerRef,
      historySyncRequestRef,
      outboxProcessingRef,
      startupAutoConnectAttemptRef,
      startupAutoConnectRetryTimerRef,
      activeRunIdRef,
      pendingTurnIdRef,
      runIdToTurnIdRef,
      setActiveRunId,
      setGatewayError,
      setSessionsError,
      setGatewayEventState,
      setIsSettingsPanelOpen,
      setIsStartupAutoConnecting,
      setIsSessionOperationPending,
      setIsBottomCompletePulse,
      clearFinalResponseRecoveryTimer,
      clearMissingResponseRecoveryState,
      clearStartupAutoConnectRetryTimer,
      clearBottomCompletePulseTimer,
      clearOutboxRetryTimer,
      invalidateRefreshEpoch,
      forceMaskAuthToken,
      runGatewayRuntimeAction,
    },
    outboxRuntimeInput: {
      isSending,
      connectionState,
      outboxQueue,
      outboxQueueRef,
      outboxProcessingRef,
      outboxRetryTimerRef,
      connectionStateRef,
      activeSessionKeyRef,
      transcriptRef,
      interimTranscriptRef,
      sendFingerprintRef,
      pendingTurnIdRef,
      activeRunIdRef,
      runIdToTurnIdRef,
      gatewaySendChat: gatewayChatSend,
      runGatewayHealthCheck,
      runGatewayRuntimeAction,
      clearOutboxRetryTimer,
      clearMissingResponseRecoveryState,
      setGatewayError,
      setGatewayEventState,
      setOutboxQueue,
      setChatTurns,
      setTranscript,
      setInterimTranscript,
      setActiveRunId,
    },
    speechRuntimeInput: {
      speechLang,
      isRecognizing,
      expectedSpeechStopRef,
      isUnmountingRef,
      setIsRecognizing,
      setSpeechError,
      setTranscript,
      setInterimTranscript,
    },
  });

  useAppRuntimeSideEffects({
    uiEffectsInput: {
      shouldShowSettingsScreen,
      forceMaskAuthToken,
      missingResponseNotice,
      activeSessionKey,
      chatTurns,
      clearMissingResponseRecoveryState,
      isTurnWaitingState,
      transcript,
      transcriptRef,
      interimTranscript,
      interimTranscriptRef,
      activeSessionKeyRef,
      historyAutoScrollRef,
      setShowScrollToBottomButton,
      gatewayUrl,
      gatewayUrlRef,
      connectionState,
      connectionStateRef,
      outboxQueue,
      outboxQueueRef,
      gatewaySessions,
      setSessions,
      gatewaySessionsError,
      setSessionsError,
      gatewayEventState,
      gatewayEventStateRef,
      isSending,
      setIsBottomCompletePulse,
      clearBottomCompletePulseTimer,
      bottomCompletePulseTimerRef,
      setGatewayEventState,
      sessionTurnsRef,
      scrollHistoryToBottom,
      isOnboardingCompleted,
      isOnboardingWaitingForResponse,
      setIsOnboardingCompleted,
      setIsOnboardingWaitingForResponse,
      isGatewayConnected,
      setIsSessionPanelOpen,
    },
    persistenceEffectsInput: {
      settingsReady,
      persistRuntimeSetting,
      activeSessionKey,
      sessionPreferences,
      outboxQueue,
      kvStore: input.kvStore,
      sessionKeyStorageKey: STORAGE_KEYS.sessionKey,
      sessionPrefsStorageKey: STORAGE_KEYS.sessionPrefs,
      outboxQueueStorageKey: STORAGE_KEYS.outboxQueue,
      identityStorageKey: OPENCLAW_IDENTITY_STORAGE_KEY,
      openClawIdentityMemory: input.openClawIdentityMemory,
      parseSessionPreferences,
      parseOutboxQueue,
      defaultSessionKey: DEFAULT_SESSION_KEY,
      activeSessionKeyRef,
      sessionTurnsRef,
      setActiveSessionKey,
      setSessionPreferences,
      setOutboxQueue,
      setGatewayEventState,
      setChatTurns,
      setLocalStateReady,
    },
    lifecycleInput: {
      localStateReady,
      settingsReady,
      gatewayUrl,
      connectionState,
      startupAutoConnectAttemptedRef,
      startupAutoConnectAttemptRef,
      connectGateway,
      isUnmountingRef,
      invalidateRefreshEpoch,
      expectedSpeechStopRef,
      holdStartTimerRef,
      historySyncTimerRef,
      historySyncRequestRef,
      historyNoticeTimerRef,
      bottomCompletePulseTimerRef,
      authTokenMaskTimerRef,
      outboxRetryTimerRef,
      startupAutoConnectRetryTimerRef,
      finalResponseRecoveryTimerRef,
      missingResponseRecoveryTimerRef,
      missingResponseRecoveryRequestRef,
      settingsFocusScrollTimerRef,
      quickTextTooltipTimerRef,
      quickTextLongPressResetTimerRef,
      quickTextLongPressSideRef,
      disconnectGateway,
    },
  });

  const appContent = useAppContentWiring({
    homeUiStateInput: {
      transcript,
      interimTranscript,
      isRecognizing,
      quickTextLeft,
      quickTextRight,
      focusedField,
      shouldShowSettingsScreen,
      isKeyboardVisible,
      isSending,
      settingsReady,
      isSessionOperationPending,
      isGatewayConnected,
      isSessionsLoading,
      sessions,
      sessionPreferences,
      sessionsError,
      isSettingsSaving,
      settingsPendingSaveCount,
      settingsSaveError,
      settingsLastSavedAt,
      isDarkTheme,
      isOnboardingCompleted,
      gatewayUrl,
      chatTurns,
      isGatewayConnecting,
      isOnboardingWaitingForResponse,
      gatewayConnectDiagnostic,
      outboxQueueLength: outboxQueue.length,
      missingResponseNotice,
      activeSessionKey,
      isMissingResponseRecoveryInFlight,
      historyRefreshNotice,
      historyLastSyncedAt,
      historyBottomInset,
      showScrollToBottomButton,
      gatewayError,
      speechError,
      gatewayEventState,
      connectionState,
      isStartupAutoConnecting,
      isBottomCompletePulse,
      isKeyboardBarMounted,
      formatClockLabel,
      getHistoryDayKey,
      getHistoryDayLabel,
      quickTextTooltipSide,
    },
    runtimeActions: {
      connectGateway,
      sendToGateway,
      refreshSessions,
      scheduleMissingResponseRecovery,
      startRecognition,
      stopRecognition,
    },
    gatewayActionHandlersHomeUiBaseInput: {
      setFocusedField,
      isMissingResponseRecoveryInFlight,
      isGatewayConnected,
      setGatewayError,
      setMissingResponseNotice,
      setHistoryRefreshNotice,
      setSpeechError,
      setIsOnboardingWaitingForResponse,
      setIsOnboardingCompleted,
      forceMaskAuthToken,
      isSessionPanelOpen,
      setIsSettingsPanelOpen,
      setIsSessionPanelOpen,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
      setSessionRenameDraft,
      canToggleSettingsPanel,
      canDismissSettingsScreen,
      transcript,
      interimTranscript,
      setTranscript,
      setInterimTranscript,
      isSessionHistoryLoading,
      clearHistoryNoticeTimer,
      activeSessionKeyRef,
      loadSessionHistory,
      setHistoryLastSyncedAt,
      showHistoryRefreshNotice,
      formatClockLabel,
      scrollHistoryToBottom,
      historyAutoScrollRef,
      setShowScrollToBottomButton,
      chatTurnsLength: chatTurns.length,
      isRecognizing,
      isSending,
      holdActivatedRef,
      holdStartTimerRef,
      composerHeight,
      setComposerHeight,
    },
    gatewayActionHandlersInput: {
      quickTextInput: {
        isRecognizing,
        setTranscript,
        setInterimTranscript,
        setQuickTextTooltipSide,
        clearQuickTextLongPressResetTimer,
        scheduleQuickTextTooltipHide,
        hideQuickTextTooltip,
        quickTextLongPressSideRef,
        quickTextLongPressResetTimerRef,
      },
      transcriptRef,
      interimTranscriptRef,
      setTranscript,
      setInterimTranscript,
      setSpeechError,
    },
  });

  const { keyboardBarAnim } = useKeyboardUiRuntime({
    showKeyboardActionBar: appContent.showKeyboardActionBar,
    setKeyboardState,
    setIsKeyboardBarMounted,
  });

  const {
    styles,
    connectionHeaderProps,
    settingsScreenModalProps,
    settingsPanelContentProps,
    sessionsScreenModalProps,
    sessionsPanelContentProps,
    homeMainLayoutProps,
  } = useAppViewModelWiring({
    appContent,
    runtimeActions: {
      connectGateway,
      refreshSessions,
      createAndSwitchSession,
      switchSession,
      isSessionPinned,
      getSessionTitle,
      startSessionRename,
      toggleSessionPinned,
      submitSessionRename,
    },
    keyboardBarAnim,
    ui: {
      isDarkTheme,
      isGatewayConnected,
      isGatewayConnecting,
      isSessionPanelOpen,
      isSettingsPanelOpen,
      canToggleSettingsPanel,
      shouldShowSettingsScreen,
      canDismissSettingsScreen,
      isKeyboardVisible,
      isRecognizing,
      isSending,
      isSessionHistoryLoading,
      isMissingResponseRecoveryInFlight,
      isKeyboardBarMounted,
      showScrollToBottomButton,
      isOnboardingWaitingForResponse,
      transcript,
      interimTranscript,
      historyScrollRef,
      isSessionsLoading,
      settingsScrollRef,
      focusedField,
      setFocusedField,
      gatewayUrl,
      setGatewayUrl,
      authToken,
      setAuthToken,
      isAuthTokenMasked,
      toggleAuthTokenVisibility,
      settingsReady,
      isStartupAutoConnecting,
      gatewayDiagnosticIconName: appContent.gatewayDiagnosticIconName,
      gatewayConnectDiagnostic,
      theme,
      setTheme,
      speechLang,
      setSpeechLang,
      quickTextInputRefs,
      quickTextLeft,
      setQuickTextLeft,
      quickTextRight,
      setQuickTextRight,
      quickTextLeftIcon,
      setQuickTextLeftIcon,
      quickTextRightIcon,
      setQuickTextRightIcon,
      ensureSettingsFieldVisible,
      connectionState,
      gatewayEventState,
      activeSessionKey,
      activeRunId,
      historyLastSyncedAt,
      startupAutoConnectAttempt: startupAutoConnectAttemptRef.current,
      sessionRenameTargetKey,
      isSessionRenameOpen,
      sessionRenameDraft,
      setSessionRenameDraft,
      isSessionOperationPending,
      sessionsError,
      formatSessionUpdatedAt,
      setIsSessionRenameOpen,
      setSessionRenameTargetKey,
    },
  });

  return {
    isDarkTheme,
    styles,
    connectionHeaderProps,
    settingsScreenModalProps,
    settingsPanelContentProps,
    sessionsScreenModalProps,
    sessionsPanelContentProps,
    homeMainLayoutProps,
  };
}
