import { StyleSheet } from 'react-native';
import {
  COMPOSER_LINE_HEIGHT,
  COMPOSER_MAX_HEIGHT,
  COMPOSER_MIN_HEIGHT,
  SEMANTIC,
} from '../logic/app-constants';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  outer: {
    flex: 1,
  },
  window: {
    flex: 1,
    width: '100%',
    overflow: 'hidden',
  },
  windowBody: {
    flex: 1,
    flexDirection: 'row',
    gap: 0,
  },
  sidebar: {
    width: 232,
    borderRightWidth: 1,
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 12,
  },
  sideChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    gap: 6,
    marginBottom: 8,
  },
  sideChipDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  sideChipText: {
    fontSize: 11,
    fontWeight: '700',
  },
  sideSeparator: {
    height: 1,
    marginVertical: 10,
  },
  sideHeader: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  sideList: {
    gap: 3,
  },
  gatewayGroup: {
    gap: 3,
    marginBottom: 4,
  },
  gatewayHeaderRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 4,
  },
  gatewayHeaderMain: {
    flex: 1,
  },
  sideItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    marginBottom: 2,
  },
  settingsNavItem: {
    paddingVertical: 10,
  },
  sideGlyphWrap: {
    width: 16,
    alignItems: 'center',
  },
  sideGlyph: {
    fontSize: 11,
    fontWeight: '800',
  },
  sideItemLabel: {
    flex: 1,
    fontSize: 13,
  },
  opacityHalf: {
    opacity: 0.5,
  },
  opacitySoft: {
    opacity: 0.65,
  },
  opacityMuted: {
    opacity: 0.7,
  },
  fontWeight500: {
    fontWeight: '500',
  },
  fontWeight600: {
    fontWeight: '600',
  },
  fontWeight700: {
    fontWeight: '700',
  },
  unreadBadge: {
    minWidth: 20,
    height: 18,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    marginLeft: 6,
  },
  unreadBadgeSmall: {
    minWidth: 18,
    height: 16,
    paddingHorizontal: 4,
  },
  unreadBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  unreadBadgeTextSmall: {
    fontSize: 9,
  },
  sessionItemDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  gatewaySessionCountBadge: {
    minWidth: 22,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
  },
  gatewaySessionCountText: {
    fontSize: 10,
    fontWeight: '700',
  },
  gatewayCollapseButton: {
    width: 28,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  gatewayCollapseButtonText: {
    fontSize: 13,
    fontWeight: '700',
    marginTop: -1,
  },
  gatewaySessionList: {
    paddingLeft: 22,
    gap: 2,
  },
  gatewaySessionItem: {
    borderRadius: 7,
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingHorizontal: 9,
  },
  gatewaySessionCreateItem: {
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  gatewaySessionItemText: {
    fontSize: 12,
  },
  newSessionButton: {
    borderWidth: 1,
    borderRadius: 8,
    minHeight: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    marginBottom: 6,
  },
  newSessionButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  sidebarGrow: {
    flex: 1,
  },
  themeSwitch: {
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 9,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  themeSwitchText: {
    fontSize: 12,
    fontWeight: '700',
  },
  content: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  homeScroll: {
    flex: 1,
    minHeight: 0,
  },
  homeScrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 14,
  },
  selectedSessionWrap: {
    flex: 1,
    minHeight: 0,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  gatewayCard: {
    borderWidth: 1.25,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 9,
    position: 'relative',
  },
  gatewayCardExpanded: {
    flex: 1,
    minHeight: 0,
  },
  gatewayCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  gatewayCardMeta: {
    flex: 1,
    minWidth: 0,
  },
  gatewayCardName: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: -0.1,
  },
  gatewayCardUrl: {
    fontSize: 11,
    marginTop: 1,
  },
  connectionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    gap: 6,
  },
  connectionChipDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  connectionChipText: {
    fontSize: 11,
    fontWeight: '700',
  },
  gatewayCardActions: {
    flexDirection: 'row',
    gap: 6,
  },
  gatewayActionHint: {
    fontSize: 10,
    fontWeight: '500',
    marginTop: 4,
  },
  gatewayRecoveryHint: {
    fontSize: 10,
    fontWeight: '500',
    marginTop: -2,
    marginBottom: 1,
  },
  inlineAction: {
    borderWidth: 1.25,
    borderRadius: 8,
    minHeight: 32,
    minWidth: 86,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlineActionText: {
    fontSize: 11,
    fontWeight: '700',
  },
  inlineActionIconText: {
    fontSize: 14,
    fontWeight: '700',
  },
  inlinePrimary: {
    borderRadius: 8,
    minHeight: 32,
    minWidth: 102,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlinePrimaryText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
  },
  inlinePrimaryIconText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  gatewayStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minWidth: 220,
    maxWidth: '70%',
  },
  statusStaticDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusRowText: {
    fontSize: 11,
    fontWeight: '600',
    flexShrink: 1,
  },
  updatedText: {
    fontSize: 11,
    fontWeight: '500',
  },
  gatewayHistoryPreview: {
    borderWidth: 1,
    borderRadius: 10,
    minHeight: 160,
    overflow: 'hidden',
  },
  gatewayHistoryPreviewCompact: {
    maxHeight: 240,
  },
  gatewayHistoryPreviewExpanded: {
    flex: 1,
    minHeight: 0,
  },
  gatewayHistoryScroll: {
    flex: 1,
  },
  gatewayHistoryScrollContent: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
  },
  gatewayHistoryScrollContentExpanded: {
    paddingBottom: 8,
  },
  attachmentList: {
    maxHeight: 40,
  },
  attachmentListContent: {
    alignItems: 'center',
    gap: 8,
    paddingVertical: 3,
    paddingHorizontal: 2,
  },
  attachmentChip: {
    maxWidth: 360,
    minHeight: 32,
    borderWidth: 1,
    borderRadius: 999,
    paddingLeft: 9,
    paddingRight: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  attachmentChipPreview: {
    width: 18,
    height: 18,
    borderRadius: 4,
  },
  attachmentChipType: {
    fontSize: 10,
    fontWeight: '700',
  },
  attachmentChipName: {
    maxWidth: 170,
    fontSize: 11,
    fontWeight: '600',
  },
  attachmentChipSize: {
    fontSize: 10,
    fontWeight: '500',
  },
  attachmentChipRemove: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  attachmentChipRemoveText: {
    fontSize: 12,
    fontWeight: '700',
    marginTop: -1,
  },
  gatewayComposerRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 6,
    zIndex: 2,
    position: 'relative',
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: 10,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  gatewayComposerRowRaised: {
    zIndex: 4,
  },
  gatewayComposerRowDropActive: {
    borderStyle: 'dashed',
  },
  quickMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  quickMenuTrigger: {
    minHeight: 36,
    minWidth: 36,
    paddingHorizontal: 0,
    borderRadius: 8,
    borderWidth: 1.25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickMenuTriggerText: {
    fontSize: 11,
    fontWeight: '700',
  },
  quickMenuIconText: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 17,
  },
  quickMenuPanel: {
    position: 'absolute',
    right: 48,
    bottom: 44,
    width: 256,
    borderWidth: 1.25,
    borderRadius: 10,
    paddingVertical: 6,
    zIndex: 5,
  },
  quickMenuItem: {
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 6,
    justifyContent: 'center',
    gap: 2,
  },
  quickMenuItemDisabled: {
    opacity: 1,
  },
  quickMenuItemTitle: {
    fontSize: 11,
    fontWeight: '700',
  },
  quickMenuItemValue: {
    fontSize: 10,
    fontWeight: '500',
  },
  composerField: {
    flex: 1,
    minHeight: COMPOSER_MIN_HEIGHT,
    maxHeight: COMPOSER_MAX_HEIGHT,
    borderWidth: 1.25,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 14,
    lineHeight: COMPOSER_LINE_HEIGHT,
    textAlignVertical: 'top',
    fontStyle: 'normal',
  },
  actionCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionSend: {
    backgroundColor: SEMANTIC.green,
  },
  actionBusy: {
    backgroundColor: '#94A3B8',
  },
  actionDisabled: {
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  actionIcon: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
    marginTop: -2,
  },
  kbdHintRowCard: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'flex-end',
    borderTopWidth: 1,
    paddingTop: 6,
  },
  attachmentStatusText: {
    flex: 1,
    fontSize: 10,
    fontWeight: '600',
    marginRight: 8,
  },
  kbdHintText: {
    fontSize: 10,
    fontWeight: '500',
  },
  settingsScroll: {
    flex: 1,
    minHeight: 0,
  },
  settingsWrap: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 14,
  },
  settingsCard: {
    borderWidth: 1.25,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 14,
    gap: 10,
  },
  settingsTitle: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: -0.1,
  },
  gatewayProfilesList: {
    gap: 8,
  },
  gatewayProfileItem: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1.25,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  gatewayProfileDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  gatewayProfileMeta: {
    flex: 1,
    minWidth: 0,
  },
  gatewayProfileName: {
    fontSize: 13,
    fontWeight: '700',
  },
  gatewayProfileUrl: {
    fontSize: 11,
    marginTop: 1,
  },
  gatewayProfileActiveTag: {
    fontSize: 11,
    fontWeight: '700',
  },
  settingsGroup: {
    gap: 4,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '600',
  },
  settingsInput: {
    height: 38,
    borderWidth: 1.25,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 13,
  },
  tokenInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tokenInputField: {
    flex: 1,
  },
  tokenMaskedField: {
    justifyContent: 'center',
  },
  tokenMaskedText: {
    fontSize: 13,
    fontWeight: '500',
    letterSpacing: 0.6,
  },
  tokenVisibilityButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1.25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeIcon: {
    width: 16,
    height: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeOutline: {
    position: 'absolute',
    width: 16,
    height: 10,
    borderWidth: 1.5,
    borderRadius: 999,
  },
  eyePupil: {
    width: 4,
    height: 4,
    borderRadius: 999,
  },
  eyeSlash: {
    position: 'absolute',
    width: 18,
    height: 1.5,
    borderRadius: 999,
    transform: [{ rotate: '-30deg' }],
  },
  settingsActionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
  },
  primaryAction: {
    flex: 1,
    minHeight: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  secondaryAction: {
    flex: 1,
    borderWidth: 1.25,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 36,
  },
  secondaryActionText: {
    fontSize: 13,
    fontWeight: '600',
  },
  gatewayConnectedHint: {
    minHeight: 30,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  gatewayConnectedDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  gatewayConnectedHintText: {
    fontSize: 11,
    fontWeight: '600',
  },
  settingsInsertRow: {
    flexDirection: 'row',
    gap: 8,
  },
  insertAction: {
    flex: 1,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1.25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  insertActionTransparent: {
    backgroundColor: 'transparent',
  },
  insertActionText: {
    fontSize: 12,
    fontWeight: '500',
  },
  quickTextHint: {
    fontSize: 10,
    marginTop: 4,
    fontStyle: 'italic',
  },
  settingsRecoveryHint: {
    fontSize: 11,
    lineHeight: 16,
    marginTop: -2,
  },
  notificationRow: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1.25,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  notificationRowTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  notificationRowTitle: {
    fontSize: 12,
    fontWeight: '600',
  },
  notificationRowDescription: {
    fontSize: 10,
    lineHeight: 14,
  },
  notificationToggleTrack: {
    width: 34,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 2,
    justifyContent: 'center',
  },
  notificationToggleThumb: {
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  notificationSectionLabel: {
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  notificationGatewayList: {
    gap: 6,
  },
  notificationGatewayRow: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1.25,
    paddingHorizontal: 10,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  notificationGatewayMeta: {
    flex: 1,
    minWidth: 0,
  },
  notificationGatewayName: {
    fontSize: 12,
    fontWeight: '600',
  },
  notificationGatewayUrl: {
    marginTop: 1,
    fontSize: 10,
    fontWeight: '500',
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  emptyWrapCompact: {
    minHeight: 130,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  emptyIconText: {
    fontSize: 14,
    fontWeight: '800',
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 5,
  },
  emptyDescription: {
    fontSize: 12,
    textAlign: 'center',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingBottom: 8,
    paddingTop: 4,
  },
  dateLine: {
    flex: 1,
    height: 1,
  },
  dateLabel: {
    fontSize: 10,
    fontWeight: '700',
  },
  turnPair: {
    paddingBottom: 11,
  },
  importedTagRow: {
    alignItems: 'flex-end',
    marginBottom: 2,
  },
  importedTag: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  importedTagText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  userRow: {
    alignItems: 'flex-end',
    marginBottom: 4,
  },
  userBubble: {
    maxWidth: '72%',
    borderRadius: 12,
    borderBottomRightRadius: 4,
    backgroundColor: '#2563EB',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  userBubbleText: {
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  assistantRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-end',
    marginBottom: 3,
  },
  assistantAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#1D4ED8',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  assistantAvatarText: {
    color: '#ffffff',
    fontSize: 8,
    fontWeight: '800',
  },
  assistantBubble: {
    flex: 1,
    minWidth: 0,
    maxWidth: 980,
    flexShrink: 1,
    borderRadius: 12,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
  },
  assistantBubbleHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 6,
    marginBottom: 6,
  },
  copyChip: {
    minHeight: 20,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyChipText: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },
  pendingBubbleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pendingBubbleText: {
    fontSize: 11,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  turnTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 2,
    marginLeft: 30,
  },
  turnStateDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  turnTimeText: {
    fontSize: 9,
    fontWeight: '500',
  },
  bootScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bootText: {
    fontSize: 14,
    fontWeight: '600',
  },
});

export default styles;
