import { useCallback } from 'react';
import { normalizeSessionKey } from '../logic/app-logic';
import useMacosAttachmentRuntime from './useMacosAttachmentRuntime';
import useMacosAppEffects from './useMacosAppEffects';
import useMacosAppLifecycle from './useMacosAppLifecycle';
import useMacosAppUiWiring from './useMacosAppUiWiring';
import useMacosComposerRuntime from './useMacosComposerRuntime';
import useMacosGatewayControllerRuntime from './useMacosGatewayControllerRuntime';
import useMacosGatewayProfileActions from './useMacosGatewayProfileActions';
import useMacosHistoryScrollRuntime from './useMacosHistoryScrollRuntime';
import useMacosNotificationRuntime from './useMacosNotificationRuntime';
import useMacosRuntimeState from './useMacosRuntimeState';
import useMacosTelemetryRuntime from './useMacosTelemetryRuntime';

export default function useMacosAppRuntime() {
  const {
    activeGatewayId,
    activeGatewayIdRef,
    activeNav,
    activeNavRef,
    activeSessionKeyRef,
    authToken,
    authTokenInputRef,
    booting,
    collapsedGatewayIds,
    composerFocusTimerRef,
    composerInputRefs,
    focusedGatewayId,
    focusedSettingsInput,
    forcedSelectionByGatewayId,
    forcedSelectionByGatewayIdRef,
    gatewayName,
    gatewayProfiles,
    gatewayProfilesRef,
    gatewayRuntimeById,
    gatewayRuntimeByIdRef,
    gatewayUrl,
    identityCache,
    identityPersistWarning,
    identityReady,
    initialAutoNavigationHandledRef,
    isAuthTokenVisible,
    isImeComposingByGatewayIdRef,
    lastAutoConnectSignatureByIdRef,
    lastHandledNotificationRouteSignatureRef,
    manualDisconnectByIdRef,
    pendingNotificationRouteRef,
    persistSettings,
    quickMenuOpenByGatewayId,
    quickTextLeft,
    quickTextRight,
    rootRef,
    sessionKey,
    setActiveGatewayId,
    setActiveNav,
    setAuthToken,
    setBooting,
    setCollapsedGatewayIds,
    setFocusedGatewayId,
    setFocusedSettingsInput,
    setForcedSelectionByGatewayId,
    setGatewayName,
    setGatewayProfiles,
    setGatewayRuntimeById,
    setGatewayUrl,
    setIdentityPersistWarning,
    setIdentityReady,
    setIsAuthTokenVisible,
    setQuickMenuOpenByGatewayId,
    setQuickTextLeft,
    setQuickTextRight,
    setTelemetrySnapshot,
    setSessionKey,
    setTheme,
    skipSubmitEditingByGatewayIdRef,
    telemetrySnapshot,
    theme,
    themeTokens,
    updateGatewayRuntime,
  } = useMacosRuntimeState();

  const {
    copyTelemetryReport,
    recordTelemetryEvent,
    resetTelemetry,
    telemetry,
  } = useMacosTelemetryRuntime({
    gatewayProfiles,
    setTelemetrySnapshot,
    telemetrySnapshot,
  });

  const {
    clearUnreadForSession,
    copiedMessageByKey,
    getPushNotificationModule,
    handleAssistantTurnArrival,
    handleCopyMessage,
    handleOpenExternalLink,
    isGatewayNotificationEnabled,
    lastNotifiedAssistantTurnByGatewayIdRef,
    notificationSettings,
    setNotificationSettings,
    toggleGatewayNotifications,
    toggleMuteForegroundNotifications,
    toggleNotificationsEnabled,
    unreadByGatewaySession,
  } = useMacosNotificationRuntime({
    activeGatewayIdRef,
    activeNavRef,
    activeSessionKeyRef,
    gatewayProfiles,
    gatewayProfilesRef,
    recordTelemetryEvent,
  });

  const {
    clearGatewayHistoryRuntime,
    composerHeightByGatewayIdRef,
    hintHeightByGatewayIdRef,
    historyBottomInsetByGatewayId,
    historyContentHeightByGatewayIdRef,
    historyScrollRefs,
    historyViewportHeightByGatewayIdRef,
    pendingTurnFocusByGatewayIdRef,
    recomputeHistoryBottomInsetForGateway,
    scheduleHistoryBottomSync,
    scheduleHistoryTurnFocus,
  } = useMacosHistoryScrollRuntime({
    gatewayProfilesRef,
    gatewayRuntimeByIdRef,
  });

  const {
    closeAllQuickMenus,
    currentSessionKeyForGateway,
    focusComposerForGateway,
    insertQuickText,
    setComposerFocusedForGateway,
    setComposerSelectionForGateway,
    setComposerTextForGateway,
    setForcedSelectionForGateway,
    setImeComposingForGateway,
    setQuickMenuOpenForGateway,
  } = useMacosComposerRuntime({
    activeGatewayId,
    composerFocusTimerRef,
    composerInputRefs,
    forcedSelectionByGatewayIdRef,
    gatewayProfiles,
    gatewayRuntimeById,
    isImeComposingByGatewayIdRef,
    sessionKey,
    setFocusedGatewayId,
    setForcedSelectionByGatewayId,
    setQuickMenuOpenByGatewayId,
    updateGatewayRuntime,
  });

  const {
    attachmentNoticeByGatewayId,
    attachmentPickerGatewayId,
    clearPendingAttachmentsForGateway,
    dropActiveByGatewayId,
    handleAttachmentPick,
    handleDroppedFilesForGateway,
    removePendingAttachmentForGateway,
    setAttachmentNoticeForGateway,
    setAttachmentPickerGatewayId,
    setDropActiveByGatewayId,
    tryImportFromClipboardShortcut,
  } = useMacosAttachmentRuntime({
    activeGatewayId,
    currentSessionKeyForGateway,
    focusComposerForGateway,
    focusedGatewayId,
    gatewayRuntimeById,
    updateGatewayRuntime,
  });

  const {
    connectGateway,
    disconnectAndRemoveController,
    disconnectGateway,
    disposeAllControllers,
    getController,
    refreshHistory,
    refreshKnownSessions,
    sendMessage,
    syncControllersWithProfiles,
  } = useMacosGatewayControllerRuntime({
    activeGatewayId,
    authToken,
    clearGatewayHistoryRuntime,
    composerInputRefs,
    currentSessionKeyForGateway,
    focusComposerForGateway,
    gatewayName,
    gatewayProfiles,
    gatewayRuntimeById,
    gatewayUrl,
    handleAssistantTurnArrival,
    identityReady,
    isImeComposingByGatewayIdRef,
    lastNotifiedAssistantTurnByGatewayIdRef,
    manualDisconnectByIdRef,
    scheduleHistoryBottomSync,
    sessionKey,
    setAttachmentNoticeForGateway,
    setForcedSelectionForGateway,
    setGatewayProfiles,
    setImeComposingForGateway,
    updateGatewayRuntime,
    recordTelemetryEvent,
  });

  const applyGatewayProfileToEditor = useCallback((profile) => {
    if (!profile) return;
    setGatewayName(profile.name);
    setGatewayUrl(profile.gatewayUrl);
    setAuthToken(profile.authToken);
    setSessionKey(normalizeSessionKey(profile.sessionKey));
    setIsAuthTokenVisible(false);
    setFocusedSettingsInput(null);
  }, [setAuthToken, setGatewayName, setGatewayUrl, setIsAuthTokenVisible, setSessionKey, setFocusedSettingsInput]);

  const {
    handleCreateGatewayProfile,
    handleCreateSession,
    handleDeleteActiveGatewayProfile,
    handleSelectGatewayProfile,
    handleSelectSession,
  } = useMacosGatewayProfileActions({
    activeGatewayId,
    applyGatewayProfileToEditor,
    clearUnreadForSession,
    connectGateway,
    disconnectAndRemoveController,
    disconnectGateway,
    focusComposerForGateway,
    focusedGatewayId,
    gatewayProfiles,
    gatewayRuntimeById,
    setActiveGatewayId,
    setActiveNav,
    setAttachmentPickerGatewayId,
    setCollapsedGatewayIds,
    setFocusedGatewayId,
    setForcedSelectionForGateway,
    setGatewayProfiles,
    setGatewayRuntimeById,
    setImeComposingForGateway,
    setQuickMenuOpenForGateway,
    setSessionKey,
    updateGatewayRuntime,
  });

  const toggleGatewayCollapse = useCallback((gatewayId) => {
    if (!gatewayId) return;
    setCollapsedGatewayIds((previous) => ({
      ...previous,
      [gatewayId]: !previous[gatewayId],
    }));
  }, [setCollapsedGatewayIds]);

  const {
    activeProfile,
    handleRootKeyDown,
    summaryChip,
  } = useMacosAppUiWiring({
    activeGatewayId,
    activeNav,
    currentSessionKeyForGateway,
    focusedGatewayId,
    gatewayProfiles,
    gatewayRuntimeById,
    getController,
    quickMenuOpenByGatewayId,
    refreshHistory,
    setQuickMenuOpenForGateway,
    updateGatewayRuntime,
  });

  useMacosAppLifecycle({
    activeGatewayId,
    activeNav,
    activeGatewayIdRef,
    activeNavRef,
    activeSessionKeyRef,
    applyGatewayProfileToEditor,
    booting,
    composerFocusTimerRef,
    disposeAllControllers,
    gatewayProfiles,
    gatewayProfilesRef,
    gatewayRuntimeById,
    gatewayRuntimeByIdRef,
    getPushNotificationModule,
    handleSelectSession,
    identityCache,
    identityReady,
    lastHandledNotificationRouteSignatureRef,
    pendingNotificationRouteRef,
    refreshHistory,
    rootRef,
    scheduleHistoryTurnFocus,
    sessionKey,
    setActiveGatewayId,
    setBooting,
    setGatewayProfiles,
    setGatewayRuntimeById,
    setIdentityPersistWarning,
    setIdentityReady,
    setNotificationSettings,
    setQuickTextLeft,
    setQuickTextRight,
    setTelemetrySnapshot,
    setTheme,
    syncControllersWithProfiles,
  });

  useMacosAppEffects({
    activeGatewayId,
    activeNav,
    activeProfile,
    applyGatewayProfileToEditor,
    attachmentNoticeByGatewayId,
    authToken,
    booting,
    clearUnreadForSession,
    closeAllQuickMenus,
    connectGateway,
    focusComposerForGateway,
    gatewayName,
    gatewayProfiles,
    gatewayRuntimeById,
    gatewayUrl,
    historyBottomInsetByGatewayId,
    identityReady,
    initialAutoNavigationHandledRef,
    lastAutoConnectSignatureByIdRef,
    manualDisconnectByIdRef,
    notificationSettings,
    pendingTurnFocusByGatewayIdRef,
    persistSettings,
    quickTextLeft,
    quickTextRight,
    telemetry,
    recomputeHistoryBottomInsetForGateway,
    refreshKnownSessions,
    scheduleHistoryBottomSync,
    scheduleHistoryTurnFocus,
    sessionKey,
    setActiveGatewayId,
    setActiveNav,
    setAttachmentNoticeForGateway,
    setCollapsedGatewayIds,
    setDropActiveByGatewayId,
    setFocusedGatewayId,
    setGatewayProfiles,
    theme,
    updateGatewayRuntime,
  });

  return {
    activeGatewayId,
    activeNav,
    activeProfile,
    attachmentNoticeByGatewayId,
    attachmentPickerGatewayId,
    authToken,
    authTokenInputRef,
    booting,
    clearPendingAttachmentsForGateway,
    collapsedGatewayIds,
    composerHeightByGatewayIdRef,
    composerInputRefs,
    connectGateway,
    copiedMessageByKey,
    currentSessionKeyForGateway,
    disconnectGateway,
    dropActiveByGatewayId,
    focusedGatewayId,
    focusedSettingsInput,
    focusComposerForGateway,
    forcedSelectionByGatewayId,
    forcedSelectionByGatewayIdRef,
    gatewayName,
    gatewayProfiles,
    gatewayRuntimeById,
    gatewayUrl,
    handleAttachmentPick,
    handleCopyMessage,
    handleCreateGatewayProfile,
    handleCreateSession,
    handleDeleteActiveGatewayProfile,
    handleDroppedFilesForGateway,
    handleOpenExternalLink,
    handleRootKeyDown,
    handleSelectGatewayProfile,
    handleSelectSession,
    hintHeightByGatewayIdRef,
    historyBottomInsetByGatewayId,
    historyContentHeightByGatewayIdRef,
    historyScrollRefs,
    historyViewportHeightByGatewayIdRef,
    identityPersistWarning,
    identityReady,
    insertQuickText,
    isAuthTokenVisible,
    isGatewayNotificationEnabled,
    isImeComposingByGatewayIdRef,
    notificationSettings,
    pendingTurnFocusByGatewayIdRef,
    quickMenuOpenByGatewayId,
    quickTextLeft,
    quickTextRight,
    recomputeHistoryBottomInsetForGateway,
    refreshHistory,
    removePendingAttachmentForGateway,
    rootRef,
    scheduleHistoryBottomSync,
    scheduleHistoryTurnFocus,
    sendMessage,
    sessionKey,
    setActiveNav,
    setAttachmentPickerGatewayId,
    setAuthToken,
    setComposerFocusedForGateway,
    setComposerSelectionForGateway,
    setComposerTextForGateway,
    setDropActiveByGatewayId,
    setFocusedGatewayId,
    setFocusedSettingsInput,
    setForcedSelectionForGateway,
    setGatewayName,
    setGatewayUrl,
    setImeComposingForGateway,
    setIsAuthTokenVisible,
    setQuickMenuOpenForGateway,
    setQuickTextLeft,
    setQuickTextRight,
    setSessionKey,
    setTheme,
    skipSubmitEditingByGatewayIdRef,
    summaryChip,
    theme,
    themeTokens,
    copyTelemetryReport,
    resetTelemetry,
    toggleGatewayCollapse,
    toggleGatewayNotifications,
    toggleMuteForegroundNotifications,
    toggleNotificationsEnabled,
    tryImportFromClipboardShortcut,
    unreadByGatewaySession,
    updateGatewayRuntime,
    telemetry,
  };
}
